### ISSUE TITLE
Wildcard Cert Support

### ISSUE THREAD

**Issue by stealthybox** [FiloSottile/mkcert#1]
Hey Filippo,
Thanks for putting together this tool -- I hacked a solution for this use case on Windows before and it was not easy to do.

The first thing I tried was to create a wildcard cert:
```
ERROR: "*.test.com" is not a valid hostname or IP
```

This regex doesn't allow asterisks which is at least part of the issue:
https://github.com/FiloSottile/mkcert/blob/master/main.go#L104

Should we support this?

Cheers! 🦄

**Comment by MintyOwl** [comment]
```go
re := regexp.MustCompile(`^[\*|0-9A-Za-z._-]+$`)
```

should be good enough

**Comment by stealthybox** [comment]
nice!
thanks @FiloSottile

**Comment by mcdado** [comment]
@FiloSottile doesn't seem to work when the second level domain is the wildcard.

```
$ mkcert *.test
Using the local CA at "/Users/David/Library/Application Support/mkcert" ✨

Created a new certificate valid for the following names 📜
 - "*.test"

The certificate is at "./_wildcard.test.pem" and the key at "./_wildcard.test-key.pem" ✅
```

![screen shot 2018-07-03 at 14 09 31](https://user-images.githubusercontent.com/898057/42219101-f96fdc7c-7eca-11e8-92d8-1e49a591f5ca.png)

![screen shot 2018-07-03 at 14 09 27](https://user-images.githubusercontent.com/898057/42219107-fc82f5a2-7eca-11e8-8114-4194a06693c8.png)
