### ISSUE TITLE
NSS DB issue

### ISSUE THREAD

**Issue by franziskuskiefer** [FiloSottile/mkcert#10]
Since [NSS 3.35](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_3.35_release_notes) sql is the default DB. So this breaks depending on the NSS version you use.

https://github.com/FiloSottile/mkcert/blob/443e5b338540eddca2fe1584216d877170201bf6/truststore_firefox.go#L79-L80

https://github.com/FiloSottile/mkcert/blob/443e5b338540eddca2fe1584216d877170201bf6/truststore_firefox.go#L83-L84

**Comment by FiloSottile** [comment]
Thanks!
