### ISSUE TITLE
firefox ssl length error

### ISSUE THREAD

**Issue by brycedorn** [FiloSottile/mkcert#101]
hey! thanks for making this - been looking for a local SSL solution for a while so hoping to add this to my workflow. I just added the url to the local url (`test.localhost`), but getting this error using firefox:

> SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG 

did some digging, and dropping firefox's TLS version from 1.3 to 1.2 (in `about:config` changing `security.tls.version.max` from **4** to **3**) was a proposed solution, but this didn't work for me. any ideas? I searched issues here and haven't seen anyone else experience this.

**Comment by twhite96** [comment]
Having the same issue, both FF and Chrome.

**Comment by FiloSottile** [comment]
Are you running an HTTPS server at test.localhost:443? Sounds like this might be the result of connecting to a plain HTTP server.

Anyway, it's likely this is an issue with the TLS implementation you are using, not with the mkcert certificates.
