### ISSUE TITLE
Chrome reporting ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY

### ISSUE THREAD

**Issue by x2rider** [FiloSottile/mkcert#107]
A search on this error reports:
A deployment of HTTP/2 over TLS 1.2 SHOULD NOT use any of the cipher suites that are listed in the cipher suite black list.

I'm not sure how to change the cipher, or possibly the cipher order.

Is there something I can to do, to fix this?

**Comment by adamdecaf** [comment]
What version of chrome are you using?

**Comment by FiloSottile** [comment]
This sounds almost certainly like an issue with the HTTPS server implementation you are using, not with the certificate mkcert generated. mkcert has no control over the cipher suites your TLS implementation uses.

If it works with any other certificate, please reopen the issue.

**Comment by x2rider** [comment]
I was able to fix the issue I was having by running the IIS Crypto 2 tool
