### ISSUE TITLE
Nothing happened after installation on Windows

### ISSUE THREAD

**Issue by yxxa** [FiloSottile/mkcert#111]
Hallo,
after i run 
`$ mkcert localhost`
and show all success message like in the README.md
but when i accessing my localhost nothing happened? 
still can't access through https?
why? is there any other configuration?

im using windows 10, and Wampserver

**Comment by ptbello** [comment]
I have a different setup but the same result: messages in powershell confirm all should've worked properly, certs exists, etc, but chrome says "This site can’t be reached - example.com.test refused to connect".
- win10 pro
- docker for windows
- pre-compiled binary mkcert-v1.2.0-windows-amd64.exe
not sure if relevant, but example.com.test runs on 127.127.2.1:80 and is forwarded to 127.0.0.1:8106 (to allow easy local domains with docker)

**Comment by moritzdietz** [comment]
@yxxa Did you configure your webserver in a way to use the certificate you just generated?

**Comment by adamdecaf** [comment]
> This sounds like the issue you guys are having is not related directly to mkcert but rather having a question related to server configuration.

I'd agree that's likely the problem. Y'all might have luck looking at https://github.com/FiloSottile/mkcert/issues/56

**Comment by FiloSottile** [comment]
mkcert just creates the certificates, you still need to configure your server to use them for HTTPS.
