### ISSUE TITLE
[feature] Read out hosts file for localhost and 127.0.0.1 aliases

### ISSUE THREAD

**Issue by pke** [FiloSottile/mkcert#112]
Would save some keystrokes if the tool would read out the hosts file optionally. All ::1, localhost and 127.0.0.1 entries could then be used as input for mkcert.
`mkcert --hosts`

Would that make sense as a PR?

**Comment by FiloSottile** [comment]
I like that mkcert is not specific to localhost (aside from the marketing), and is not tied to any way of directing traffic (hosts files, docker IPs, staging servers...), so I think that tips the scales towards not including this, although I see it could be useful. It could also easily be a wrapper script.
