### ISSUE TITLE
How to delete Local CA

### ISSUE THREAD

**Issue by sumitanvekar** [FiloSottile/mkcert#114]
While running mkcert -install, i provided a password which I can't remember. Is there a way to delete local CA and create it again?

**Comment by adamdecaf** [comment]
Yep! 

```
# Remove the CA from trust stores
$ mkcert -uninstall
Using the local CA at "/Users/adam/Library/Application Support/mkcert" ✨
Password:
The local CA is now uninstalled from the system trust store(s)! 👋
```

You could then remove the certs at `/Users/adam/Library/Application Support/mkcert` if you wanted.

**Comment by sumitanvekar** [comment]
Sorry if I didn't make myself clear. I forgot the password which I entered when running $ mkcert -install
So, I can't run uninstall as well.

Is it ok if I uninstall mkcert itself and then delete certs in the directory? Will that clean up Local CA?

**Comment by sumitanvekar** [comment]
Closed it by mistake :(

**Comment by adamdecaf** [comment]
You'll probably want to manually remove them from each truststore, but yea that should work.

**Comment by sumitanvekar** [comment]
I uninstalled mkcert itself and then deleted "/Users/adam/Library/Application Support/mkcert". That seemed to work.

Thanks!
