### ISSUE TITLE
[Question] How to add Root CA with chromium installed by snap

### ISSUE THREAD

**Issue by AlexandrePavy** [FiloSottile/mkcert#116]
Hello, 

Nice project work as a charm :+1:, 

I have a little question, I use chromium with snapcraft.

When i do `mkcert -install` this add Root CA in default path for chrome (and work fine this default chrome on linux) but not with chromium browser installed by snap 

![image](https://user-images.githubusercontent.com/6603411/50995253-dea3f500-151e-11e9-8e1e-20abd4d84cd6.png)

Default path for Root CA is `sql:$HOME/.pki/nssdb` but with snap is `sql:/home/alexandre/snap/chromium/current/.pki/nssdb`.

Do you have an idea for it to work in my case ? Can we change the default path of root CA? What is the certutils command for add the root ca in my chromium?

**Comment by adamdecaf** [comment]
Can you try adding support for that path in the NSS code? We should support both options. 

https://github.com/FiloSottile/mkcert/blob/master/truststore_nss.go#L16

**Comment by AlexandrePavy** [comment]
Yes add snap path should be great.

as workaround, you can add manually Root CA with this command

`certutil -d sql:/home/<HomeName>/snap/chromium/current/.pki/nssdb -A -t "C,," -n 'mkcert dev' -i /home/<HomeName>/.local/share/mkcert/rootCA.pem`

**Comment by adamdecaf** [comment]
@AlexandrePavy would you be able to pull down [this Pull Request](https://github.com/FiloSottile/mkcert/pull/121) and try? 

Branch: https://github.com/adamdecaf/mkcert/tree/more-nss-locations

**Comment by AlexandrePavy** [comment]
Hello @adamdecaf,

I have just tried PR, sorry for the delay ! 

![image](https://user-images.githubusercontent.com/6603411/52536515-f8be3680-2d5b-11e9-8ed0-84248e65074c.png)

firstly I delete the existing certificate
![image](https://user-images.githubusercontent.com/6603411/52536527-168b9b80-2d5c-11e9-9b05-2ca87fd2e0f4.png)

Then when I reinstall the certificat, I have no added certificate for the chrome snap :
![image](https://user-images.githubusercontent.com/6603411/52536533-24d9b780-2d5c-11e9-9659-ae88bc88842e.png)

it does not seem to work or did I do something wrong?

**Comment by shaal** [comment]
Using Ubuntu 18.10
On a [DDEV 1.8.0](https://github.com/drud/ddev/releases/tag/v1.8.0) project, I installed `mkcert -install`.

It works great on Google Chrome and Firefox.
But does NOT work on Chromium and on Firefox Nightly.

**Comment by adamdecaf** [comment]
@shaal can you confirm of the above additional paths would work to install and trust the certificate on your machine?
