### ISSUE TITLE
ERROR: no Firefox and/or Chrome/Chromium security databases found

### ISSUE THREAD

**Issue by Artarex** [FiloSottile/mkcert#120]
Hey. I installed mkcert via rpm -Uvh harbottle-main-release*rpm
yum install mkcert
On my centos 7.

When i try to use "mkcert -install" it gives me the following error
"Using the local CA at "/root/.local/share/mkcert" ✨
ERROR: no Firefox and/or Chrome/Chromium security databases found
"

Any idea how to fix this?

**Comment by adamdecaf** [comment]
Do you know where the database is? I assume on centos it's not at `$HOME/.pki/nssdb"`.

**Comment by Artarex** [comment]
Hey. 
Maybe in etc/pki/nssdb ?
I have a cert8, cert9, key3 key4 and secmod.db in this folder
What do I need to change that it works?

**Comment by adamdecaf** [comment]
@Artarex would you be able to pull down [this Pull Request](https://github.com/FiloSottile/mkcert/pull/121) and try? 

Branch: https://github.com/adamdecaf/mkcert/tree/more-nss-locations

**Comment by Artarex** [comment]
Thanks for the fast response. Would it be possible to create a pre build binary for me? 
My Centos has some problems with compiling Go, and I dont have the time the next 2-3 days to try to fix it.
So i would appreciate a pre build binary
Thanks

**Comment by adamdecaf** [comment]
@FiloSottile Do you object to me uploading a binary? 

```
$ git log -n1 
commit a37de7396998699097a7e4877fbf1c185d471c13 (HEAD -> more-nss-locations, adamdecaf/more-nss-locations)
Author: Adam Shannon <adamkshannon@gmail.com>
Date:   Wed Jan 16 18:05:19 2019 -0600

    nss: look in more locations for cert/key database

$ GOOS=linux go build -o mkcert-linux . 

$ zip mkcert-centos.zip mkcert-linux 
  adding: mkcert-linux (deflated 50%)

$ shasum -a256 mkcert-centos.zip 
f9cb839d331d52bd80a036daa3ad15086ea210351bf5e591f8cc4632f6fb4f22  mkcert-centos.zip
```

**Comment by Artarex** [comment]
I compiled the source on windows and moved the new compiled mkcert file to my bin folder and replaced the old one. 
mkcert -install did not give me an error this time.
However i did not get these 2 messages:
"The local CA is now installed in the system trust store! ⚡️
The local CA is now installed in the Firefox trust store (requires restart)! 🦊"

So thats my console output:

`[root@wph5ak0 ~]# mkcert -install
Using the local CA at "/root/.local/share/mkcert" ✨
[root@wph5ak0 ~]#
`

**Comment by adamdecaf** [comment]
Do you know if the Firefox binary is installed somewhere other than `/usr/bin/firefox`?

**Comment by Artarex** [comment]
My Centos7 had no Firefox binary. 
Now something strange happened.
I installed firefox via yum install firefox and now the firefox binary is in the right directory.

If I do now mkcert -install it gives the same error again

Created a new local CA at "/root/.local/share/mkcert" 💥
The local CA is now installed in the system trust store! ⚡️
ERROR: no Firefox and/or Chrome/Chromium security databases found

Tje databases are still at the same location in etc/pki/nssdb
![1](https://user-images.githubusercontent.com/15215220/51289828-06ed9100-1a02-11e9-97ee-251bfe582b38.png)

**Comment by adamdecaf** [comment]
I had to start Firefox/Chrome and load an HTTPS page before the NSS database was written.

**Comment by RAM1160** [comment]
test your path to mkcert : mkcert -CAROOT
if its /root/.local/share/mkcert you have to uninstall mkcert and reinstall it without root
mkcert -install
the path should look something like this:
home/YourAccount/.local/share/mkcert
FF & Chrome do not allow certs from root

Hope that helps

**Comment by timelytree** [comment]
> I had to start Firefox/Chrome and load an HTTPS page before the NSS database was written.

Thanks @adamdecaf! This did it for me.

**Comment by Letlaka** [comment]
> I had to start Firefox/Chrome and load an HTTPS page before the NSS database was written.

This worked for me too, Thanks!

**Comment by 144mdgross** [comment]
> I had to start Firefox/Chrome and load an HTTPS page before the NSS database was written.

same! this also worked for me
