### ISSUE TITLE
Not able to export on Android 9 

### ISSUE THREAD

**Issue by ValSbo** [FiloSottile/mkcert#128]
Hi, i'm not able to export a cert on my Android mobile.
I exported a cert yesterday and it worked, now i'm trying to export another certificate and it doesn't work.
Any advice?

**Comment by FiloSottile** [comment]
Can you describe exactly what you are doing, what you expect to happen, and what happens instead?

**Comment by ValSbo** [comment]
I solved it, i was exporting a certificate in a format that android doesn't recognize. 
Thank you!
