### ISSUE TITLE
mkcert ruined my localhost:8080

### ISSUE THREAD

**Issue by tr1s** [FiloSottile/mkcert#129]
I had to run [these commands](https://shopify.github.io/slate/docs/create-a-self-signed-ssl-certificate) in order to get [slate](https://shopify.github.io/slate/docs/create-a-self-signed-ssl-certificate) to work, it never worked... Then I found some hacks in the github issues of slate, it finally worked by creating some keys in my project.

Now when I run webpack-dev-server on my own personal projects using my [boilerplate](https://github.com/tr1s/tris-webpack-boilerplate), localhost:8080 doesn't work anymore, none of them do. I tried doing mkcert install and mkcert localhost and it created my keys, but still nothing.. I get this below.

<img width="1680" alt="cleanshot 2019-02-05 at 11 51 43 2x" src="https://user-images.githubusercontent.com/19172250/52289637-6cb3a580-293c-11e9-8048-a67e24b68d49.png">

How do I get things back to normal? I don't want all these extra steps just to run my personal projects. All I had to do before was type "npm start" and everything was ready to go. Ever since me setting up _one_ slate project everything else is ruined so far.

Any ideas? How can I fix this?

**Comment by FiloSottile** [comment]
ERR_SSL_PROTOCOL_ERROR suggests that the issue has nothing to do with the certificate and key that mkcert generates, but is a problem with whatever HTTPS/TLS implementation you are using.

**Comment by tr1s** [comment]
@FiloSottile so what do I do about this?

I know for a fact that everything was fine before I brew installed mkcert and set up this slate project. I can't even get my static freelance projects running right now. I didn't change any code whatsoever in my other projects. How do I revert back from all this?

**Comment by FiloSottile** [comment]
i'm sorry to hear this, but it sounds like it worked before you started using HTTPS and TLS, so you have to find out what software you are using for HTTPS and TLS and what the issue with it is. mkcert does not run any code after generating the certificate and key files.

**Comment by tr1s** [comment]
@FiloSottile Can you give me some sort of direction?

I created a webpack boilerplate, I used webpack cli/webpack-dev-server, I run npm start and everything works as it should. I have no extra software that's making me use HTTPS/TLS. I just made a config and everything worked.

Now that I have mkcert nothing works. I don't really know what you're telling me here about extra software. There is no extra software. Nothing I'm trying is fixing this so far

**Comment by FiloSottile** [comment]
I know next to nothing about the Node.js ecosystem, but I assume you did not just run mkcert, you probably also changed some options to tell your server to load the certificate mkcert created. That's the HTTPS code that would be having issues.

(If not, have you tried loading http://localhost:8080 instead of https://?)

**Comment by tr1s** [comment]
I went through my command history and I think these two got the slate project to work. Does that mean anything to you?

I went through the install process from the mkcert docs recently to try and override it but nothing happens. Http just get's forced to https to answer your question.

<img width="654" alt="cleanshot 2019-02-05 at 16 08 03 2x" src="https://user-images.githubusercontent.com/19172250/52304265-56b7dc00-2960-11e9-9337-8ef0c30873e5.png">
<img width="726" alt="cleanshot 2019-02-05 at 16 08 16 2x" src="https://user-images.githubusercontent.com/19172250/52304268-57e90900-2960-11e9-854c-608a6e67fefe.png">
<img width="428" alt="cleanshot 2019-02-05 at 16 10 15 2x" src="https://user-images.githubusercontent.com/19172250/52304353-91ba0f80-2960-11e9-9cea-acfc06c5fa09.png">

**Comment by tr1s** [comment]
<img width="1197" alt="cleanshot 2019-02-05 at 16 12 25 2x" src="https://user-images.githubusercontent.com/19172250/52304491-de054f80-2960-11e9-99ae-39d93b5c483d.png">

**Comment by tr1s** [comment]
@FiloSottile is there a way I can fully revert this and delete anything and everything mkcert created? I need to abandon this slate project so I can fix everything else asap.

**Comment by tr1s** [comment]
Feel free to close this. I had to recover my mac from the day before this happened.

**Comment by HarleyLiddell13** [comment]
On Feb 5, 2019 10:06 PM, Tristan Michael Lawrence <notifications@github.com> wrote:

Feel free to close this. I had to recover my mac from the day before this happened.

**Comment by FiloSottile** [comment]
I'm sorry to hear that. If you have further problems with HTTPS  aside from the certificate itself, it looks like the name of the project you need to open an issue in is "Slate".

**Comment by skywinston** [comment]
The solution to this problem can be found here:
https://github.com/Shopify/slate/issues/726#issuecomment-431372434

**Comment by saurabhsethi1102** [comment]
You can always use a private window to route to http://localhost

**Comment by iulianalbu** [comment]
@saurabhsethi1102 Yea, your idea it's working, but for Postman not.

@tr1s I manage to fixed this issue

- I removed all related stuff to mkcert using https://github.com/FiloSottile/mkcert/issues/208
- I searched for _mkcert_ inside my **Keychain Access** and delete all the things related to _mkcert_
- I **sync all my Chrome data with my account** and after that **I reset Chrome to the default values**  and after I connected with my account and all things were working

**Comment by Drjacky** [comment]
Same here! Working with Ktor, and after [this](https://youtrack.jetbrains.com/issue/KTOR-2858/Getting-error-ktor.application-Failed-to-decode-request-on-newly-created-ktor-project-with-the-latest-idea-eap2.1.2.4416.7#focus=Comments-27-9170877.0-0), it fixed my issue; I could see the Welcome page. Then I installed mkcert and it ruined my setup! [Uninstalling all the certs it created and itself](https://github.com/FiloSottile/mkcert/issues/208#issuecomment-541457624) didn't help either

Unfortunately this is no an option for me:
> I had to recover my mac from the day before this happened.

**Comment by Drjacky** [comment]
> Same here! Working with Ktor, and after [this](https://youtrack.jetbrains.com/issue/KTOR-2858/Getting-error-ktor.application-Failed-to-decode-request-on-newly-created-ktor-project-with-the-latest-idea-eap2.1.2.4416.7#focus=Comments-27-9170877.0-0), it fixed my issue; I could see the Welcome page. Then I installed mkcert and it ruined my setup! [Uninstalling all the certs it created and itself](https://github.com/FiloSottile/mkcert/issues/208#issuecomment-541457624) didn't help either
> 
> Unfortunately this is no an option for me:
> 
> > I had to recover my mac from the day before this happened.

In this case, you need to define a new port; not sure where and how, but the ruined address(locahost) and port is cached!

**Comment by raul-rtl** [comment]
same here, after installing mkcert it ruined my setup, I tried [iulianalbu](https://github.com/iulianalbu) solution but not success

**Comment by Jeffxz** [comment]
This helped me on chrome https://stackoverflow.com/questions/25277457/google-chrome-redirecting-localhost-to-https
What I did was enter `chrome://net-internals/#hsts`, query for "localhost", if there is any hit then delete "localhost" and it worked for me.

**Comment by MisterDr** [comment]
In my case solution was rather simple. Since I am using VSCode and it has ugly habit to forward the ports on whatever it sees at the console, I simply removed forwarded ports. Double check to see if anything else is listening on your development port.
