### ISSUE TITLE
Secure connection failed

### ISSUE THREAD

**Issue by iampeterbanjo** [FiloSottile/mkcert#130]
I tried using `mkcert` with these steps

- Install mkcert CA and certificates
``` bash
mkcert -install 
mkcert "*.site.localhost" site.localhost localhost 127.0.0.1 ::1
```
- open Firefox and go to https://localhost

But then I got the error 

> Secure Connection Failed
> An error occurred during a connection to localhost:8080. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG
>   The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>   Please contact the web site owners to inform them of this problem.

**Comment by FiloSottile** [comment]
Are you actually configuring your server to use the certificates and support HTTPS? That looks like the server is trying to answer with plain HTTP.

**Comment by iampeterbanjo** [comment]
Thanks for the quick response.

I'm using a Node.js server and I've done `export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"`.

Is that enough?

**Comment by FiloSottile** [comment]
No, that's sufficient to configure clients to trust mkcert certificates, not to configure servers to use them. I'm afraid I can't help you configure your server as I know next to nothing about the Node.js ecosystem, sorry.
