### ISSUE TITLE
add an option to specify pkcs12 file password

### ISSUE THREAD

**Issue by youlinxiaozhu** [FiloSottile/mkcert#132]
The password of pkcs12 file is currently hard coded into source. I want to generate a pkcs12 file for program that only support blank password.

**Comment by adamdecaf** [comment]
This has been asked as a change before, see https://github.com/FiloSottile/mkcert/pull/58#issuecomment-451782395

**Comment by FiloSottile** [comment]
I'm sorry to hear there are programs that only support blank passwords, but it looks like there are more that hardcode "changeit" and my opinion on adding a configuration option for it has not changed.

You'll have to use openssl(1) to remove the password, I'm afraid.
