### ISSUE TITLE
SEC_ERROR_LEGACY_DATABASE

### ISSUE THREAD

**Issue by tim-field** [FiloSottile/mkcert#134]
Using the latest binary I'm getting the following error in ubuntu 16.10

```
./mkcert -install
Using the local CA at "/home/tim/.local/share/mkcert" ✨
ERROR: failed to execute "certutil -A": exit status 255

certutil: function failed: SEC_ERROR_LEGACY_DATABASE: The certificate/key database is in an old, unsupported format.
```

There are a couple issue that reference this, but they are both closed #12  so not sure if this is a regression ?

**Comment by adamdecaf** [comment]
What version of Firefox/Chrome are you using? 16.10 might have the older cert8.db format, but that should still be supported by mkcert.

**Comment by tim-field** [comment]
Firefox 65 ( default browser ) 
Chrome 72.0.3626.96 (Official Build) (64-bit)

**Comment by adamdecaf** [comment]
Those should both be on cert9.db, so the problem might be permissions or path related. Did `mkcert` output any additional debug information? 

You're on v1.3.0, right? Did any debug tips from https://github.com/FiloSottile/mkcert/issues/12 give more information?

**Comment by tim-field** [comment]
I've downloaded the latest version, and even tried building from source.

I get no other output then what I have pasted above.

It's not clear to me what debugging options I have or that a referenced in #12

**Comment by tim-field** [comment]
Ok I looked in profile ~/.mozzila/firefox  and found a few profiles, all seemed to still be using cert8.db  

I removed this directory, and started firefox again, and mkcert now works!  So something up with my firefox install then, not updating its cert database.
