### ISSUE TITLE
New certificate "appears to be expired"

### ISSUE THREAD

**Issue by selfagency** [FiloSottile/mkcert#138]
I just created a new certificate for a project on my local machine. But when I load up the site, I get the following error:

"Websites prove their identity via certificates, which are valid for a set time period. The certificate for local.test appears to be expired."

Examining the certificate, it says creation date is June 29, 2017 and the expiration date is June 29, 2018.

Very odd and confusing. What's happening here?

**Comment by selfagency** [comment]
Never mind, it was an Nginx issue.

**Comment by rossPatton** [comment]
Currently having this problem, could you elaborate on how you resolved this?

**Comment by rfay** [comment]
Please check that you are using v1.4.0, especially if macOS Catalina is involved. Versions prior to v1.4.0 could not be valid on Catalina.
