### ISSUE TITLE
support installing arbitrary cert/ca 

### ISSUE THREAD

**Issue by adamdecaf** [FiloSottile/mkcert#14]
Many companies have internal CAs and wish for them to be installed. If `-install` took a certificate that would allow operators a "one command" type install. 

```
$ mkcert -install company-ca.pem 

$ cat company-ca.pem | mkcert -install
```

**Comment by FiloSottile** [comment]
I am not at all opposed to making a library out of the install feature, and then making a separate tool to install any root, but I want to keep this tool focused on its use case.
