### ISSUE TITLE
Allow setting pfx password

### ISSUE THREAD

**Issue by robrich** [FiloSottile/mkcert#140]
Right now the pfx password is "changeit" (thanks #86 for showing it). This is ok, but I must break out openssl to change it.  Can we add a parameter so I can pass in this password so I get the cert I want in one shot?

**Comment by adamdecaf** [comment]
This has been asked about before and since it's an old format unlikely to be customizable. https://github.com/FiloSottile/mkcert/pull/58#issuecomment-451782395

**Comment by robrich** [comment]
Sounds like a completely acceptable answer.  Bummer that ASP.NET Core still uses pfx as their primary format.
