### ISSUE TITLE
Create certificate with multiple Subject Alternative Names

### ISSUE THREAD

**Issue by akash1810** [FiloSottile/mkcert#144]
Hi,

Would it be possible to create a certificate with multiple Subject Alternative Name entries? The use case here is to be able to use a single cert for multiple domains rather than a cert per domain.

**Comment by FiloSottile** [comment]
Just do `mkcert san1.com san2.com`.

**Comment by akash1810** [comment]
🤦‍♂️ thanks! Upon rereading the docs, I see it now, albeit quite subtly documented.

```
$ mkcert example.com "*.example.org" myapp.dev localhost 127.0.0.1 ::1
Using the local CA at "/Users/filippo/Library/Application Support/mkcert" ✨

Created a new certificate valid for the following names 📜
 - "example.com"
 - "*.example.org"
 - "myapp.dev"
 - "localhost"
 - "127.0.0.1"
 - "::1"
```

Thank you for this library btw!
