### ISSUE TITLE
EV SSL

### ISSUE THREAD

**Issue by badaoshen** [FiloSottile/mkcert#146]
how can I get SSL like this,a EV-SSL!
![image](https://user-images.githubusercontent.com/23612126/53887000-475da880-405c-11e9-8beb-f1fe03eec01e.png)

**Comment by FiloSottile** [comment]
EV is complicated (to the point that it might not be possible to do from a local CA) and has no technical consequences (making it not useful for mkcert, which is only a development tool), so it's out of scope.
