### ISSUE TITLE
Virus scanner detects windows release as infected

### ISSUE THREAD

**Issue by kaiwa** [FiloSottile/mkcert#153]
It's a false positive for sure, but this can be quite an issue with company networks where users are not allowed to configure exceptions for the virus scanner.

Virustotal.com shows no match for Bitdefender (only for McAffee), but on a colleague's windows system Bitdefender detects the exe as virus as well.

Is there anything you can do to prevent that false positive? 

Tested with that release: https://github.com/FiloSottile/mkcert/releases/download/v1.3.0/mkcert-v1.3.0-windows-amd64.exe

Scan result:

> McAfee-GW-Edition
> BehavesLike.Win64.VirRansom.rh

https://www.virustotal.com/gui/file/546ad2acbf74ddad79e47d2fe86fe851aa25012822fec7c656b565dbb82a23ed/detection

![Bildschirmfoto von 2019-04-11 09-18-50](https://user-images.githubusercontent.com/319268/55938115-db61f780-5c3a-11e9-9567-a2a928a7e23e.png)

**Comment by FiloSottile** [comment]
This is unfortunate, but it happens with Go binaries, and I can imagine that adding roots to the system store is also something that annoys AV engines.

I don't think there's anything I can do here, but if you could report it as a false positive to the AV vendor, I'd appreciate it.

**Comment by loeffe1** [comment]
Same is happening to me using Avira Pro. HEUR/APC (Cloud) detected and access blocked. I have reported this to the vendor.
