### ISSUE TITLE
mac work fine but "password" always request on client certificates

### ISSUE THREAD

**Issue by matth-c3** [FiloSottile/mkcert#157]
Hello, 

Thanks for that amazing too. Everything is working smoothly, except that when I connect to the website using chrome, after I select the client certificate I always get this popup asking for my password. Is there a way to get ride of it ? 

I followed the instruction : 

`mkcert -install`
then `mkcert "*.exemple.com" example.com localhost 127.0.0.1`
followed by  `mkcert -client -pkcs12 "*.example.com" example.com locahost 127.0.0.1`

I use the `export` variable also for node. 

![image](https://user-images.githubusercontent.com/30625765/56216848-76efcf80-6062-11e9-8e2b-5379db85bd63.png)

It happens only from a new window, maybe it's required by chrome to access the keystore ? 

Thanks.

**Comment by FiloSottile** [comment]
How did you install the client certificate?

If you move it from the System keychain to the login one, does it solve it?

**Comment by matth-c3** [comment]
Hello @FiloSottile ,

It's the same. Both ( CA and client ) are in the login keychain but it still ask me for the password.

Thanks
