### ISSUE TITLE
Trouble on install on linux

### ISSUE THREAD

**Issue by rifkytech** [FiloSottile/mkcert#158]
i want to install mkcert from brew, & show error :

> pi@raspberrypi:~ $ brew install mkcert
Updating Homebrew...
==> Installing dependencies for mkcert: go
==> Installing mkcert dependency: go
==> Downloading https://dl.google.com/go/go1.12.3.src.tar.gz
Already downloaded: /home/pi/.cache/Homebrew/downloads/db77615ab69139f8c1ce0273b27aacd84f7e09074312136f82aaa7b0dbb37d3d--go1.12.3.src.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz
Already downloaded: /home/pi/.cache/Homebrew/downloads/04b57725e4f47b10e87a6a8bd5e2ff1fcf5b3d0528c8c380be25ace54607c9e2--go1.7.linux-amd64.tar.gz
==> ./make.bash --no-clean
Last 15 lines from /home/pi/.cache/Homebrew/Logs/go/01.make.bash:
2019-04-16 16:04:00 +0000
./make.bash
--no-clean
Building Go cmd/dist using /tmp/go-20190416-26205-gq88p6/go/gobootstrap.
./make.bash: line 167: /tmp/go-20190416-26205-gq88p6/go/gobootstrap/bin/go: cannot execute binary file: Exec format error
READ THIS: https://docs.brew.sh/Troubleshooting

How to solve this?

**Comment by adamdecaf** [comment]
I think the linuxbrew formula needs to download for ARM rather than amd64.

https://storage.googleapis.com/golang/go1.7.linux-arm64.tar.gz

I don't see docs on how to support linuxbrew's mkcert formula for this. [They only mention it's best effort](https://github.com/Homebrew/brew/blob/fe41710a83e9997c6044fb184ebdde3ace594209/docs/Homebrew-on-Linux.md#arm). The [linuxbrew mkcert formula](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/mkcert.rb#L12) has been modified to support linux on amd64 though.

**Comment by moritzdietz** [comment]
You don't have to use brew on your Raspberry Pi at all if the formula is broken.

For example, currently, you'd download the latest available version of mkcert pre-compiled by the maintainer. Which is nice so you don't have to compile it yourself!

1. `sudo wget https://github.com/FiloSottile/mkcert/releases/download/v1.3.0/mkcert-v1.3.0-linux-arm -O /usr/local/bin/mkcert`
2. `sudo chmod +x /usr/local/bin/mkcert`
3. Run `mkcert`

Done. Hope this helps.

**Comment by FiloSottile** [comment]
This is a Homebrew on Linux issue, as it's failing to install Go, before it even gets to mkcert.

**Comment by neocamel** [comment]
> You don't have to use brew on your Raspberry Pi at all if the formula is broken.
> 
> For example, currently, you'd download the latest available version of mkcert pre-compiled by the maintainer. Which is nice so you don't have to compile it yourself!
> 
> 1. `sudo wget https://github.com/FiloSottile/mkcert/releases/download/v1.3.0/mkcert-v1.3.0-linux-arm -O /usr/local/bin/mkcert`
> 2. `sudo chmod +x /usr/local/bin/mkcert`
> 3. Run `mkcert`
> 
> Done. Hope this helps. Please make sure to close this issue if this has resolved your problem!

I'm following your directions but when I type 'mkcert', I get 'bash: mkcert: command not found'

**Comment by aindriu80** [comment]
thanks  moritzdietz  - Worked for me - Ubuntu server on Raspberry Pi

**Comment by appel** [comment]
FWIW, as of Jan 23, 2022, this is what worked for me on my Pi 4 running Ubuntu 21.10:

- `sudo wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-arm -O /usr/bin/mkcert`
- `sudo chmod +x /usr/bin/mkcert`
- Run `mkcert`
