### ISSUE TITLE
Install CA certificate from a remote mkcert

### ISSUE THREAD

**Issue by Toilal** [FiloSottile/mkcert#163]
I'm running a windows host with mkcert installed on a Linux VM, but there's no easy way to install the mkcert root CA inside Windows host.

from windows Host, I would like to run `mkcert -install -url https://192.168.1.100:9999/ca.pem`.

The `ca.pem` could be published on the Vagrant VM side with `mkcert -serve-ca 9999`.

Would you accept a pull request for this feature ?

**Comment by adamdecaf** [comment]
Network file transfers are complicated. What about copying the needed file (or generated certificate for windows) outside of mkcert?

**Comment by FiloSottile** [comment]
I think this falls outside the scope of mkcert.

The instructions for how to do it manually are at https://github.com/FiloSottile/mkcert#installing-the-ca-on-other-systems
