### ISSUE TITLE
After mkcert I get "Potential Security Risk" warning

### ISSUE THREAD

**Issue by ralvez** [FiloSottile/mkcert#164]
I installed mkcert in ArchLinux.
Installation was smooth. No issues, no warnings.
I run 

> mkcert -install and mkcert localhost.

 Everything was fine and I was "told" by the installer that Firefox and Chrome/Chromium had been included.

I then run in my dev environment:

>  npx vue-cli-service serve --https --port 8040

The server started on https://localhost:8040 but ... when I go to the page I get warnings of not being secure. 
Also while testing a mailchip api the browser rejects the connection due to CORS given that my connection is not secure.
Could you help me fix these problems.
Thanks!!

**Comment by adamdecaf** [comment]
You might need to configure node.js to look at the mkcert CA location. Maybe https://github.com/FiloSottile/mkcert/issues/78#issuecomment-428636441 ?

**Comment by ralvez** [comment]
I very rarely reboot my system, however, a couple of days ago I did due to a kernel update and  then when I started once again tinkering with mkcert it stated working just fine... go figure. :)
Thanks for your reply.

**Comment by FiloSottile** [comment]
Probably it took a browser restart, glad it works now!
