### ISSUE TITLE
can't load package: package github.com/FiloSottile/mkcert

### ISSUE THREAD

**Issue by hassan-plt** [FiloSottile/mkcert#170]
:~/mkcert-1.0.0$ sudo make
GOPATH="/.GOPATH" go install -v github.com/FiloSottile/mkcert
can't load package: package github.com/FiloSottile/mkcert: cannot find package "github.com/FiloSottile/mkcert" in any of:
	/usr/lib/go-1.10/src/github.com/FiloSottile/mkcert (from $GOROOT)
	/.GOPATH/src/github.com/FiloSottile/mkcert (from $GOPATH)
Makefile:5: recipe for target 'mkcert' failed
make: *** [mkcert] Error 1

**Comment by FiloSottile** [comment]
It looks like you are using an old version of mkcert. The current one is 1.3.0 and does not have a Makefile. Please follow the [installation instructions](https://github.com/FiloSottile/mkcert#linux), and open a new issue if there is a problem with the current version.
