### ISSUE TITLE
Can we customize the Certificate Attributes of CA while generating CA with mkcert 

### ISSUE THREAD

**Issue by shijukuchelan1985** [FiloSottile/mkcert#175]
Hi All, 

It would be great if someone tells me how to customize the Certificate Attributes while generating CA with mkcert. Please let me know the feature is already available, if yes, how to modify CN, OU, O, issued by, etc. 
   
 Thanks a lot,

**Comment by shijukuchelan1985** [comment]
I think I found it, closing the ticket 👍

**Comment by ddnexus** [comment]
@shijukuchelan1985 Happy you found it, but happier if you could share it! ;)
HOW?

**Comment by AndreSchwarzer** [comment]
@shijukuchelan1985 It would be nice if you share your finding

**Comment by marcbachmann** [comment]
That's not yet supported according to the code https://github.com/FiloSottile/mkcert/blob/2a46726cebac0ff4e1f133d90b4e4c42f1edf44a/cert.go#L59-L74

**Comment by m2acgi** [comment]
https://github.com/txthinking/mad can customize the Certificate Attributes
