### ISSUE TITLE
What is the "Password:" for which I'm prompted when I run `mkcert -install` on a Mac?

### ISSUE THREAD

**Issue by kenny-evitt** [FiloSottile/mkcert#178]
From a *Terminal* window:

```
$ mkcert -install
Created a new local CA at "/Users/kenny/Library/Application Support/mkcert" 💥
Password:
```

I'm pretty sure this is my Keychain password (the 'login' password for my user) but it's certainly not clear that that's what's being requested. Could this (or should) this be documented in the README? (I'd be willing to make a stab at doing so if it's considered helpful.)

**Comment by hauleth** [comment]
Current account password. The same you use when you do `sudo true`

**Comment by rfay** [comment]
This is a confusing thing that mkcert silently runs sudo. Maybe necessary, but a little more output would be useful, knowing that sudo may go ahead and prompt for password.

**Comment by hauleth** [comment]
Actually, at least in macOS Sierra, it is not needed to use `sudo` for `security` command line tool, as this will automatically ask user whether they allow changes and would even allow using TouchID to confirm such changes.

**Comment by adamdecaf** [comment]
I created https://github.com/FiloSottile/mkcert/pull/183 and it works locally on my machine.

**Comment by FiloSottile** [comment]
We should probably always pass `--prompt="Sudo password:"` to `sudo`.

**Comment by kenny-evitt** [comment]
@FiloSottile That's a good idea too but a brief mention in the README would nicely set expectations too:

 - [Note `sudo` requirement by kenny-evitt · Pull Request #185 · FiloSottile/mkcert](https://github.com/FiloSottile/mkcert/pull/185)

**Comment by adamdecaf** [comment]
I like the idea of passing `--promtp` to `sudo`.
