### ISSUE TITLE
Running mkcert -install as root on Linux doesn't install into the Java trust store

### ISSUE THREAD

**Issue by darioseidl** [FiloSottile/mkcert#182]
Probably a user error, but maybe the documentation/output could be improved.

I used `mkcert` successfully on my local machine, then tried the same on our CI server (Debian stretch) and got:

```
root@ci:~# export JAVA_HOME="$(dirname $(dirname $(readlink -f $(which java))))"
root@ci:~# echo $JAVA_HOME 
/usr/lib/jvm/java-11-openjdk-amd64
root@ci:~# mkcert -install
Using the local CA at "/root/.local/share/mkcert" ✨
The local CA is now installed in the system trust store! ⚡️
```

No mention of the java trust store. It would be good if there was some output/warning about what went wrong. It took me a while to figure out that apparently I shouldn't run `mkcert` as root. Running the same commands as a different user works (and asks for `sudo` password).

Btw. when running `mkdir -install` a second time, there is also no mention of the java trust store.

First time:
```
user@ci:~$ mkcert -install
Using the local CA at "/home/user/.local/share/mkcert" ✨
Installing to the system store is not yet supported on this Linux 😣 but Firefox and/or Chrome/Chromium will still work.
You can also manually install the root certificate at "/home/user/.local/share/mkcert/rootCA.pem".
The local CA is now installed in Java's trust store! ☕️
```
Second time:
```
user@ci:~$ mkcert -install
Using the local CA at "/home/user/.local/share/mkcert" ✨
Installing to the system store is not yet supported on this Linux 😣 but Firefox and/or Chrome/Chromium will still work.
You can also manually install the root certificate at "/home/user/.local/share/mkcert/rootCA.pem".
```

**Comment by FiloSottile** [comment]
I _think_ all you are seeing is that `-install` does not print anything if the certificate is already installed. Otherwise, it's a bug. Can you check with v1.4.1 when it comes out later today? I added "already installed" messages.

BTW, the "not yet supported on this Linux" is #188, fixed now.

**Comment by darioseidl** [comment]
Thanks, I'll give it a try. v1.4.1 is not out yet, is it?

**Comment by darioseidl** [comment]
I tried it now with v1.4.1 (sorry for the long delay) and I get a message `The local CA is already installed in Java's trust store! 👍`, so this is fixed.
