### ISSUE TITLE
Firefox Nightly might need a separate cert installation?

### ISSUE THREAD

**Issue by lgarron** [FiloSottile/mkcert#184]
Just just updated Firefox Nightly and it told me that it's storing data in a new, separate profile. At the same time, me local cert stopped working in Nightly. Perhaps the cert needs to be installed for Nightly separately?

**Comment by FiloSottile** [comment]
Can you try rerunning `mkcert -install`?

**Comment by lgarron** [comment]
Ah, that works — excellent! :-D

I guess this can get a bit confusing — I guess I installed the cert a few minutes before I opened the updated Nightly today. But this seems like pretty reasonable behaviour now.
