### ISSUE TITLE
mkcert with zsh

### ISSUE THREAD

**Issue by electricarts** [FiloSottile/mkcert#190]
Hi, 

sorry for the probably stupid question, but I'm more of a pixel pusher than a terminal guy. I switched from bash to zsh under Mac OS X (10.14.6). I copied everything from .bash_profile and .bashrc into .zshrc. Now I get the error message zsh: command not found: mkcert when calling mkcert.  I set the terminal back to bash and everything works. What am I doing wrong?

Mario

**Comment by electricarts** [comment]
Found it. If you come from bash you might have to change your $PATH. This must be in .zshrc: 

`export PATH=$HOME/bin:/usr/local/bin:$PATH`

Maybe it helps others.

**Comment by FiloSottile** [comment]
Yep, depending how you installed it, you'll have to make sure the shell PATH includes the binary directory!
