### ISSUE TITLE
mkcert -install (v1.4.0) fails to run in Ubuntu 16.04: SEC_ERROR_READ_ONLY

### ISSUE THREAD

**Issue by rfay** [FiloSottile/mkcert#192]
Ubuntu 16.04, linuxbrew-installed mkcert v1.4.0, mkcert -install fails with certutil error:

```
mkcert -install
Created a new local CA at "/home/circleci/.local/share/mkcert" 💥
The local CA is now installed in the system trust store! ⚡️
ERROR: failed to execute "certutil -A": exit status 255

certutil: function failed: SEC_ERROR_READ_ONLY: security library: read-only database.
```

**Comment by rfay** [comment]
On Debian 9 this doesn't seem to be a problem?
On Ubuntu 18.04, it prompts for sudo password and succeeds.

**Comment by rfay** [comment]
On Manjaro (and probably arch the same) using linuxbrew it prompts for sudo password successfully and works.

**Comment by rfay** [comment]
I think #193 will solve this problem in a fairly generic way. It might also be possible and simpler to always use sudo on certutil.

**Comment by topher200** [comment]
I'm experiencing this issue when testing an Azure pipeline on both Ubuntu 16.04 and 18.04.

```
+ mkcert -install --cert-file certificate.pem --key-file key.pem lh.wordstream.com
Created a new local CA at "/home/vsts/.local/share/mkcert" 💥
The local CA is now installed in the system trust store! ⚡️
ERROR: failed to execute "certutil -A": exit status 255

certutil: function failed: SEC_ERROR_READ_ONLY: security library: read-only database.
```

Using @rfay's binaries from #193 resolved the issue for me.
```
wget https://github.com/rfay/mkcert/releases/download/v1.4.1-alpha1/mkcert-v1.4.1-alpha1-linux-amd64 -O bin/mkcert
```
