### ISSUE TITLE
scoop install mkcert, download url is not valid in window

### ISSUE THREAD

**Issue by houchaowei** [FiloSottile/mkcert#194]
when i run
```
scoop install mkcert
```
in window shell .
and i dot know what should i do after this

**Comment by houchaowei** [comment]
![image](https://user-images.githubusercontent.com/17643027/63517577-ca4ac080-c521-11e9-8334-fd90ba6f69e2.png)

**Comment by houchaowei** [comment]
anyone else knows how to solve this

**Comment by FiloSottile** [comment]
This in not an issue with the mkcert project, but with scoop, as I seem to be able to download that file correctly. Please report this at https://github.com/lukesampson/scoop-extras/issues.

**Comment by houchaowei** [comment]
tks for yr answer, i will do it right now
