### ISSUE TITLE
Silent [No verbose]

### ISSUE THREAD

**Issue by Krato** [FiloSottile/mkcert#196]
Hello, first thanks for this amazing tool.

I'm developing a bash file to create vhosts for my mac environment. I'm able to create a cert using mkcert, but the terminal shows all the ouput of mkcert.

There is an option to hide the ouput?

Thanks!

**Comment by FiloSottile** [comment]
mkcert simply sends output to stderr, so if you want to hide it in a script, you can use `2> /dev/null` and check the exit code to make sure there were no errors.
