### ISSUE TITLE
PKCS#12 support

### ISSUE THREAD

**Issue by linux-china** [FiloSottile/mkcert#20]
it's great tool :)  it's friendly for Golang developer.   Did you have any plan to generate PKCS12 for Java developer,  and they will execute command to convert pem to PKCS12.  command as following: 
```
openssl pkcs12 -export -in example.com.pem -inkey example.com-key.pem -out example.com.p12 -name mkcert -CAfile rootCA-key.pem -caname root
```

**Comment by FiloSottile** [comment]
PKCS#12 is a dying format and its use should be discouraged. Moreover, the only Go encoder I could find only supports password-protected bundles.

So I'm not inclined to implement this myself, but if enough people need it I'm willing to merge a PR.

**Comment by linux-china** [comment]
@FiloSottile  I submitted a pull request with PKCS#12 generation. Please review it.
