### ISSUE TITLE
setting up multiple computers with same .pem file generated by mkcert

### ISSUE THREAD

**Issue by junduan125** [FiloSottile/mkcert#200]
Hi, this might be a rookie question.

I have an unqiue development network setup at work. If I serve my https web page  "example.org", not only I see "example.org" on my machine locally, but also other developers on their machines within the same network see "example.org".

If I run on my own machine:
```
mkcert -install
mkcert example.org
```
It configures my windows computer so that my browser doesn't complain when I visit https://example.org served with example-key.pem and example-cert.pem.

Is there a quick and easy way of also configuring my co-workers' machines to use mkcert with example-key.pem and example-cert.pem generated for my machine so that their browser wouldn't complain either?

**Comment by FiloSottile** [comment]
Try these instructions and let me know if they are not clear enough!

https://github.com/FiloSottile/mkcert#installing-the-ca-on-other-systems

**Comment by junduan125** [comment]
Thanks for the quick response!

from #123, I found 2 ways of changing the $CAROOT variable
```
 $ CAROOT=~/local_certificates mkcert -install
```
or changing the ~/.bashrc file
```
export CAROOT="$HOME/local_certificates"
```
Does editing system environment variable in control panel in windows work? 
i.e. adding a new entry under system variables
Variable        |     Value
$CAROOT         "C:\dev\local_certificates"

Also, once the rootCA.pem is installed, is it safe to remove the rootCA.pem file?

**Comment by FiloSottile** [comment]
Yes, system wide env vars should also work.

You can delete rootCA.pem after installing, yes.

I'll close this now, but let us know if there are ways we can improve the instructions.
