### ISSUE TITLE
mkcert -install keeps telling me that "keytool is not available", when it is?

### ISSUE THREAD

**Issue by CaerphillyMediaLtd** [FiloSottile/mkcert#201]
I keep getting:

    Warning: "keytool" is not available, so the CA can't be automatically installed in Java's trust store! ⚠️

When it plainly is available, I can just type "keytool" and it works. JAVA_HOME is set just fine. I'm really at a loss because everything else can access it just fine.

**Comment by FiloSottile** [comment]
Weird! Can you give us the output of `which keytool` and `echo $PATH`? Are you running mkcert with sudo, maybe?

**Comment by FiloSottile** [comment]
Timing out in "waiting for info", feel free to open a new issue with the debug info!

**Comment by ajith-sdet** [comment]
> Weird! Can you give us the output of `which keytool` and `echo $PATH`? Are you running mkcert with sudo, maybe?

Observed same issue due to wrong path in JAVA_HOME, once correct path is present, issue wasn't observed. Thanks for the tip 'which keytool` and `echo $PATH', helped me to resolve it.

**Comment by monchyrcg** [comment]
Hi @ajith-sdet what is the JAVA_HOME correct path?  echo $PATH return these:
`/Users/xxxxxx/bin:/Users/xxxxxx/.dotfiles/modules/dotly/bin:/Users/xxxxxx/.dotfiles/bin:/Library/Java/JavaVirtualMachines/amazon-corretto-15.jdk/Contents/Home/bin:/Users/monchyrcg/.gem/bin:/Users//.go/bin:/Users//.cargo/bin:/usr/local/opt/ruby/bin:/usr/local/opt/python/libexec/bin:/opt/homebrew/bin:/usr/local/bin:/usr/local/sbin:/bin:/usr/bin:/usr/sbin:/sbin`
