### ISSUE TITLE
Certificate not trusted in iOS 13

### ISSUE THREAD

**Issue by broizter** [FiloSottile/mkcert#202]
My certificate is no longer trusted since upgrading to iOS 13. I'm guessing it has to do with the new requirements introduced in iOS 13.

https://support.apple.com/en-us/HT210176

**Comment by FiloSottile** [comment]
What version of mkcert did generate them? This should be fixed in v1.4.0. See #174.

**Comment by broizter** [comment]
Sorry about that. Creating new certificates with v1.4.0 did indeed fix the problem. Closing this issue.

**Comment by x4080** [comment]
@broizter I seems have problem with this too, do you use the root certificate for the server or the generated certificate after calling mkcert (it will create xxxx.key and xxxx-key.pem) ? And which certificate do you install in the device ?

Thanks

**Comment by bmitchinson** [comment]
I'm also still having trouble with a cert on iOS 13.3.1, even thought that same cert is fine on OSX 10.15.3

**Comment by miguelmota** [comment]
Make sure that after importing the rootCA.pem into iOS that you go to the Settings app and then "General -> About -> Certificate Trust Settings" to enable full trust for the root certificate.

**Comment by seeya** [comment]
I'm on iOS 14 and the root certificate doesn't appear on the page "Certificate Trust Settings".

**Comment by edwardfhsiao** [comment]
> I'm on iOS 14 and the root certificate doesn't appear on the page "Certificate Trust Settings".

Probably you have not including both files in ```Profiles```?

![image](https://user-images.githubusercontent.com/11728228/122195383-e83c9e80-cec8-11eb-8137-86484fe0f64f.png)


Because I don't have "Enable full trust for root certificates," until I put ```rootCA.pem``` in iPhone as well as the documentation says https://github.com/FiloSottile/mkcert#installing-the-ca-on-other-systems

```copy it to a different machine```
