### ISSUE TITLE
How to customize CN?

### ISSUE THREAD

**Issue by ddnexus** [FiloSottile/mkcert#204]
I need a certificate with a specific Common Name. I didn't find any doc about that. Is it possible to customize? Thanks.

**Comment by FiloSottile** [comment]
We don't support this, you can see some of the reasons at #205

**Comment by ddnexus** [comment]
Thanks for your answer. 

We understood that trying to use mkcert for our particular case was not a good idea for quite a few reasons.

We opt for a quite simple custom script that automates the creation of the CA root + a star-domain certificate and their addition to proxy server, java-truststore, FF trustore, etc.

**Comment by DoraTheExploder** [comment]
I've discovered that if you use an external tool to generate a Certificate Signing Request (.csr) such as [DigiCert CSR Tool](https://www.digicert.com/easy-csr/openssl.htm) (or do it manually with openssl), you can customize the relevant fields and then pass it as a sort of configuration file to mkcert with `$ mkcert -csr <domain>`.

I have not tested using a CSR for initial Root CA installation, but `$ mkcert --help` implies that it should be possible.
