### ISSUE TITLE
Why subject doesn't contain CN for generated certs?

### ISSUE THREAD

**Issue by shadyabhi** [FiloSottile/mkcert#205]
The typical generated cert via mkcert has subject as:-

```
subject= /O=mkcert development certificate/OU=username@hostname
```

While most web certs also have a CommonName attribute. 

```
➤ openssl s_client -servername www.google.com -connect "www.google.com:443" </dev/null 2>&1| openssl x509 -noout -subject -issuer
subject= /C=US/ST=California/L=Mountain View/O=Google LLC/CN=www.google.com
issuer= /C=US/O=Google Trust Services/CN=GTS CA 1O1
```

Is there a reason behind this design choice?

I can see that CommonName is ignored while creating the cert. 
https://github.com/FiloSottile/mkcert/blob/df15e0c1efd3b2f372170e6866cac54df720e724/cert.go#L61-L64
Later, for PKCS#12, there's a CommonName added but not for usual default options, why?

**Comment by FiloSottile** [comment]
Common Name has been deprecated for about 20 years, and is now ignored by major X.509 verifiers. It's an overloaded unconstrained field that should stop being used for web certificates.

Unfortunately, IIS and iOS use it in their UIs, so mkcert sets it in the root and in PKCS#12 certificates.

**Comment by shadyabhi** [comment]
@FiloSottile Would you accept a PR to add CN if the user needs it or is that out of scope for this project and the direction it wants to head in?

**Comment by FiloSottile** [comment]
Unfortunately, making the certificates look like production certificates is out of scope. The CN is a fairly small change, but mkcert certificates are pretty opinionated, and mkcert would have to grow a large number of config options to allow everyone to make certificates similar to those they already have. I have seen a few forks made in these situations, and I think that's the way to go, as it gives you complete control over how the certificates look like.

**Comment by will** [comment]
I was hoping to switch from my stack of [incomprehensible `openssl` commands](https://github.com/will/crystal-pg/blob/cafe5bfee163355f56456946b8dbf402235d7696/.github/setup.sh#L13-L19) to `mkcert` to generate both server certs (this works) and also client certs (this does not work) to test [my postgres driver](github.com/will/crystal-pg). 

It is impossible to use `mkcert` to generate postgres client certs because postgres uses the cn attribute to map the provided client cert to the requested database user name https://www.postgresql.org/docs/current/auth-cert.html

I appreciate that this is an opinionated tool, and you do not want to support this feature. But I figured maybe this was a use of cn you were not aware of. I will return to my nightmare stack of openssl commands.

**Comment by marcgardent** [comment]
"Common Name has been deprecated for about 20 years, and is now ignored by major X.509 verifiers. "

    curl: (60) schannel: SNI or certificate check failed: SEC_E_WRONG_PRINCIPAL (0x80090322) 
    More details here: https://curl.se/docs/sslcerts.html

curl, chrome and lot of program havent yet received the mkcert's service note.

In additionnaly, we install the ROOT certificate in the system store to able to suppress SSL errors.
this no make sense if the CN not set also.


Windows alternative with valid certificate! :) OMG....

```powershell
choco install openssl
choco upgrade openssl
$domain="mydomain.local"
openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes -keyout "$($domain).key" -out "$($domain).crt" -subj "/CN=$($domain)." -addext "subjectAltName=DNS:$($domain),DNS:*.$($domain),IP:127.0.0.1"
Import-Certificate -FilePath .\$($domain).crt -CertStoreLocation Cert:\CurrentUser\Root
```

**Comment by ToxicMushroom** [comment]
> Common Name has been deprecated for about 20 years, and is now ignored by major X.509 verifiers. It's an overloaded unconstrained field that should stop being used for web certificates.
> 
> Unfortunately, IIS and iOS use it in their UIs, so mkcert sets it in the root and in PKCS#12 certificates.

Could you provide a link ? 
I found https://datatracker.ietf.org/doc/html/rfc2818#section-3.1but it is about http over TLS, but how does that apply to strange technologies like LDAPS ?
