### ISSUE TITLE
Wildcard certificates on Safari, macOS Catalina

### ISSUE THREAD

**Issue by anmartini** [FiloSottile/mkcert#206]
On macOS Catalina I can not use wildcard certificates with Safari.

They work fine on Chrome and Firefox, but Safari (13.0.2 and Technology Preview) complains that "Certificate name does not match input".

I have the same problem with old and new certificates, with and without multiple names.
Certificates with multiple names work with the non-wildcard names (e.g. a certificate for "domain.test" and "*.domain.test" works fine with https://domain.test but fails with https://sub.domain.test)

![wildcard](https://user-images.githubusercontent.com/2474517/66596385-136fd600-eb9d-11e9-93ae-7016a97e5633.png)

**Comment by rfay** [comment]
I just tested on Catalina, Safari, and used a hostname that figured in a wildcard, and it seemed to work ok. 

If you're not using mkcert v1.4, please do upgrade to it. I assume you must be using 1.4 or probably nothing would work. 

<img width="886" alt="Screenshot_10_10_19__1_02_PM" src="https://user-images.githubusercontent.com/112444/66598479-5ced0080-eb5e-11e9-97fe-e7dfe606fd9c.png">

<img width="472" alt="Screenshot_10_10_19__1_02_PM" src="https://user-images.githubusercontent.com/112444/66598501-66766880-eb5e-11e9-9d38-c103d9d0f32a.png">

**Comment by rfay** [comment]
Interesting. I know that a real CA could never issue a cert for a .test domain... so maybe they've written this into the browser?

**Comment by anmartini** [comment]
The strange thing is that with non-wildcard names it works with .test domains.
I also had problems with cookies, that weren't shared between sub domains when using .test.
I'll close the issue as this seems to me a problem with Safari, but maybe it could be useful to add a warning in mkcert.

**Comment by ruimarinho** [comment]
I am also experiencing the same issue with a wildcard `.test` domain on macOS Catalina running v1.4.1.

**Comment by kamui545** [comment]
I've got the same issue and I believe it is due to ATS ([App Transport Security](https://developer.apple.com/security/)), both Safari and iOS Simulator cannot connect to my API.

You can check like this:

```console
nscurl --ats-diagnostics https://domain.test // pass
nscurl --ats-diagnostics https://subdomain.domain.test // fail
```

I can also confirm that it is a Catalina thing... 10.14 does not have this problem AFAIK.

**Comment by landabaso** [comment]
Thanks so much @anmartini @ruimarinho @kamui545 for sharing your findings with .test domains, cookies, subdomains & Safari.

I've spent a couple of days banging my head trying to understand why I could share subdomain cookies on my production .com server but not on my .test development server.

In fact I opened this thread on SO because I felt hopeless:
https://stackoverflow.com/questions/62023857/sharing-cookies-across-test-sub-domains-in-safari-13-not-possible

So, what would you guys recommend? Not using .test but using .local? What about .localhost? Any other random extension?

From what you said, it looks like .test is somehow hardcoded into Safari. Did you find any way to make it possible to use .test extension after your original posts?

Thanks!

**Comment by anmartini** [comment]
Hey,
I didn't find any solution other than changing the domain from .test to .local.
In other projects I used a "regular" public domain, putting it in /etc/hosts file and creating a certificate with mkcert. This is probably the method that gave me less problems with cookies and cors issues.

**Comment by landabaso** [comment]
Thanks @anmartini. I switched to .local and cookies work again. ".test" domains bring these problems. Also wildcard domain certificates were not working for ".test". They should really be avoided on MacOs.

**Comment by Kichikahunov** [comment]
Thanks! I had the same problems with cookies and certs, after switching from test to local everything works again!

**Comment by landabaso** [comment]
Safari is a nightmare. Is anyone now also having CORS issues with .local domains in Safari? I think something changed again.

**Comment by anmartini** [comment]
I had problems with CORS and cookies even with .local, I've now switched to "fake" but regular TLDs, like .work, .dev.
It really is a nightmare. 😞
