### ISSUE TITLE
How does one completely uninstall this library?

### ISSUE THREAD

**Issue by SHxKM** [FiloSottile/mkcert#208]
Thanks for the useful library, however I'd like to uninstall it + remove this:

> Warning: the rootCA-key.pem file that mkcert automatically generates gives complete power to intercept secure requests from your machine. Do not share it.

Where is `rootCA-key.pem`?

**Comment by rfay** [comment]
`mkcert -uninstall` will remove the root CA from your browser and system
`rm -r "$(mkcert -CAROOT)"` will then remove the root CA from your home directory. 
Then you can remove mkcert however you installed it. Probably just `rm $(which mkcert)`

**Comment by FiloSottile** [comment]
Indeed, the `mkcert -uninstall` step is the important one, as it makes `rootCA-key.pem` powerless.

**Comment by SHxKM** [comment]
@FiloSottile If I did `brew uninstall mkcert` and then `sudo find / -name rootCA-key.pem`, and deleted `mkcert`'s folder from Application Support, am I set?

**Comment by FiloSottile** [comment]
No, that will make a new root, and then uninstall that new one, not the previous one.

It's so you can have multiple independent CAROOTs.

**Comment by felipevalois** [comment]
@FiloSottile I have tried all of the above but the certificate still keeps showing up. What should I do?

**Comment by npivaut** [comment]
> `mkcert -uninstall` will remove the root CA from your browser and system `rm -r "$(mkcert -CAROOT)"` will then remove the root CA from your home directory. Then you can remove mkcert however you installed it. Probably just `rm $(which mkcert)`

Thanks :)

**Comment by RoniWasHere** [comment]
I can't get rid of this !

Chrome is not "forgetting" this certificate no matter what!

I've removed with `mkcert -uninstall` 
I did `rm -r "$(mkcert -CAROOT)"` 
I did `brew remove mkcert`

And still, chrome thinks my local domain is not working because of this

![Screenshot 2023-01-31 at 17 15 38](https://user-images.githubusercontent.com/121748797/215800287-89137ca5-d017-43f4-a10d-fe6e46be934f.png)

**Comment by rfay** [comment]
All the things you did uninstall the CA, not the cert. You seem to have a certificate installed somewhere, even though you deleted the CA. Remove the cert and key from whatever webserver is serving this.

**Comment by RoniWasHere** [comment]
The site is in docker, I've replaced the certificates with REAL ONES from Let's Encrypt, from a working server.

**Comment by rfay** [comment]
You haven't quite succeeded yet in replacing the certs.

**Comment by RoniWasHere** [comment]
I have removed all the generated cert files, rebuilt the dockerfile, pruned all volumes. 
want to point out suggestions instead of telling useless comments?

**Comment by rfay** [comment]
I'm just telling you that your webserver is still using a cert that you don't want it to use. This is a problem with your configuration. I understand that you think you've taken care of it, but you haven't. I can't help you beyond that. I won't reply any further.  

Note that if you build certs into your Docker image you may be making a big mistake security-wise.

**Comment by ipfreer** [comment]
check your browser store and related. you've trusted that cert in past, then deleted hierarchy above it now browser is not trust it again. if you manually trusted it in chrome it may have "pinned" it somewhere, or it's in browser storage for 6mo, or in persistent cache, etc etc so browser have snapshot to refer to, to detect and protect against any changes! it also seems to me big Corp and gov doesn't like the masses have access to such crypto, only overpaid, insecure and unsafe, but still somehow certified and recognized, CA's get that nod for easy approval. Even Let's Encrypt! they don't like that development at all, see EFF whole story on it all, then look at state of brokenness for certs, hell there are official CA's right now that are not even CA's! lol
check Chrome browser, and Android (if applicable) developer docs and forums for how developers use local certs all the time to test features before rolling to public. I think that will help you find where that cert is easier than try get Dev of this project to answer something his project didn't do.
HTH-sincerely)

**Comment by RoniWasHere** [comment]
@rfay 
> Note that if you build certs into your Docker image you may be making a big mistake security-wise.

Why on earth would you think that I'm doing it? all I did, was install mkcert on my mac, generated a certificate for my local website - put it in a VOLUME so that nginx container can use it to serve the site to the browser. that's it.

I'm using the basic `nginx:latest` tag - no creating my own image.

**Comment by nickretallack** [comment]
I'm having issues with this as well.  How do you delete a cert that was installed with mkcert?  On Mac OS.

**Comment by rfay** [comment]
`mkcert -install` installs a CA (Certificate Authority). It does not install certificates. You can *create* certificates with it and you could use those various ways. 

If you want to remove the CA, you would do `mkcert -uninstall` and then optionally remove the directory shown by `mkcert -CAROOT`. If you have created certs and then used them somewhere, you just have to sort that out.

**Comment by monty62** [comment]
Thank you for what you do and Happy Thanksgiving

**Comment by Baluditor** [comment]
For anyone having this problem, follow these [instructions](https://www.codeproject.com/Articles/1010667/SSL-Connection-Error-When-Debugging-via-Localhost). This is the missing step here (at least it was for me).
