### ISSUE TITLE
`go run github.com/FiloSottile/mkcert` no longer works outside with Go 1.14

### ISSUE THREAD

**Issue by eliasnaur** [FiloSottile/mkcert#209]
The fix for https://github.com/golang/go/issues/32027 disallows `go run` and friends outside a module (when GO111MODULE=on):

    $ GO111MODULE=on go run github.com/FiloSottile/mkcert
    cannot find module providing package github.com/FiloSottile/mkcert: working directory is not part of a module

**Comment by FiloSottile** [comment]
Sigh, it was too good for this world.
