### ISSUE TITLE
Command to get the path of or copy the ca certificate

### ISSUE THREAD

**Issue by schrej** [FiloSottile/mkcert#21]
I'm using this tool with vagrant. The services within vagrant need to communicate with each other and therefore need the ca to accept the certificates.
To add the ca I first need to get the certificate. While it is rather easy to find a command to simplify it even more would be nice.

One or both of the following might be useful:
`mkcert -capath` that just returns the path to `rootCA.pem`
`mkcert -cacopy <path>` that copies the `rootCA.pem` to `<path>`

As this tools aims to make stuff as easy as possible this might be a good addition as it takes away the extra step figuring out the path of the ca certificate.

**Comment by nebloc** [comment]
@schrej Something like [this?](https://github.com/nebloc/mkcert)

**Comment by schrej** [comment]
As the names of the files are always the same that would be good, yes.
