### ISSUE TITLE
Can I use it on the LAN network?

### ISSUE THREAD

**Issue by chaihongjun** [FiloSottile/mkcert#210]
There is a server (IP:192.168.0.222 ) in the LAN, I have configured it with the LAN DNS service (dnsmasq), and this server is also doing Web services. Now I want to install mkcert on it, as a CA certificate organization.Will it work?

**Comment by rfay** [comment]
A cert verifies the *domain name* not any IP address. The verification happens in your browser or other client though.

However, you seem to be talking about generating certs on a server and trying to trust them on clients. That will require you to have the clients trust the CA. See https://github.com/FiloSottile/mkcert/blob/master/README.md#installing-the-ca-on-other-systems for a general approach.

What we do is essentially:
* Install CA on server and clients
* Run mkcert -install on server
* Copy that CA to clients per the readme and `mkcert -install` it on the clients
* Now certs generated on the server are trusted by the clients.

**Comment by i300220** [comment]
What if the client is Windows XP?  I know it's obsolete but I still use it on one dedicated computer.  Your amd64 mkcert won't work there.  I tried to put the cert in %Appdata%/mkcert but don't know whether or not it's enough.

Second question.  What if I have 2 servers on my LAN and I want to generate certs for both (could be identical I don't care) and use the cert(s) on the LAN clients.

Your method works well for 1 server actually.  I'm not keen to experiment with 2 servers.  Hence my question.

Best regards, and thanks for that awesome tool.  It's long time need.  In fact who os the best to certify a certificate if not oneself.  Certainly not greedy companies that keep your key for a fee on top of that.  It.s  a LAN.

Best!

**Comment by maxsyst** [comment]
hello world, anyone can use like "https://192.168.101.2" get the green tag visit servie?
