### ISSUE TITLE
mkcert as local user getting Not: not found

### ISSUE THREAD

**Issue by wizonesolutions** [FiloSottile/mkcert#222]
I'm running mkcert as a local Docker container user in order to get it installed into the NSS DB so that it will work with headless Chrome (and Selenium) in a Docker container. I've used this approach successfully in a different container, but in this one (selenium/standalone-chrome-debug) I'm hitting a strange error that I'm not quite sure how to diagnose or debug.

Command: output

```
$ TRUST_STORES=nss mkcert -install
/usr/local/bin/mkcert: 1: /usr/local/bin/mkcert: Not: not found
```

From what I can tell, the tool is getting unexpected output and trying to execute that output. When I tried another invocation of this (with `sudo -E` in case permissions were an issue), it failed on line 26 of `sh`.

It's running Ubuntu:

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

I install mkcert in the Dockerfile with:

```
ENV MKCERT_VERSION=v1.4.0
RUN sudo su -c 'apt-get update && \
  apt-get install -y curl openssl libnss3-tools && \
  curl -sSL https://github.com/FiloSottile/mkcert/releases/download/$MKCERT_VERSION/mkcert-$MKCERT_VERSION-linux-amd64 -o /usr/local/bin/mkcert && \
  chmod +x /usr/local/bin/mkcert && \
  apt-get purge -y curl && apt-get clean && \
  chmod +x /selenium2-startup.sh'
```

And I see paths to the expected binaries with `which`, etc.

**Comment by wizonesolutions** [comment]
Ah. The contents of `/usr/local/bin/mkcert` are `Not Found`, so I guess the URL changed from last time I used it. That'll do it! Closing this.

**Comment by wizonesolutions** [comment]
P.S. link was fine, my switch to single quotes when porting my Dockerfile from headless Chrome to Selenium was the culprit. Obviously a literal `$MKCERT_VERSION` won't work.

**Comment by aureate-labs-team** [comment]
> I'm running mkcert as a local Docker container user in order to get it installed into the NSS DB so that it will work with headless Chrome (and Selenium) in a Docker container. I've used this approach successfully in a different container, but in this one (selenium/standalone-chrome-debug) I'm hitting a strange error that I'm not quite sure how to diagnose or debug.
> 
> Command: output
> 
> ```
> $ TRUST_STORES=nss mkcert -install
> /usr/local/bin/mkcert: 1: /usr/local/bin/mkcert: Not: not found
> ```
> 
> From what I can tell, the tool is getting unexpected output and trying to execute that output. When I tried another invocation of this (with `sudo -E` in case permissions were an issue), it failed on line 26 of `sh`.
> 
> It's running Ubuntu:
> 
> ```
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 18.04.2 LTS
> Release:        18.04
> Codename:       bionic
> ```
> 
> I install mkcert in the Dockerfile with:
> 
> ```
> ENV MKCERT_VERSION=v1.4.0
> RUN sudo su -c 'apt-get update && \
>   apt-get install -y curl openssl libnss3-tools && \
>   curl -sSL https://github.com/FiloSottile/mkcert/releases/download/$MKCERT_VERSION/mkcert-$MKCERT_VERSION-linux-amd64 -o /usr/local/bin/mkcert && \
>   chmod +x /usr/local/bin/mkcert && \
>   apt-get purge -y curl && apt-get clean && \
>   chmod +x /selenium2-startup.sh'
> ```
> 
> And I see paths to the expected binaries with `which`, etc.

You should try "**./mkcert -install**"
