### ISSUE TITLE
Chromium 78 rejects importing key

### ISSUE THREAD

**Issue by luke-jr** [FiloSottile/mkcert#230]
Tried to import the key into Chromium:

```
Certification Authority Import Error
The file contained one certificate, which was not imported:
mkcert development certificate: Not a Certification Authority
```

Chromium Version 78.0.3904.87

**Comment by FiloSottile** [comment]
Can you provide us the steps you followed to import the key? I am not entirely sure what that means.

**Comment by luke-jr** [comment]
Ran `mkcert router.lan 192.168.1.1` which made a `.pem` and `-key.pem` file pair.

Opened up `chrome://settings/certificates` in Chromium. Selected the `Authorities` tab.

Clicked `Import` and selected the [bare] `.pem` file. Checked "Trust this certificate for identifying websites" and `OK`.

Then I get the error.

**Comment by FiloSottile** [comment]
It sounds like Chromium wants the issuer to be imported there, not the leaf certificate ("Not a Certification Authority"). You'll find your mkcert CA with `mkcert -CAROOT`.

Note that the default way to make your mkcert certificates trusted is to use `mkcert -install` to get the root automatically into the system trust store.
