### ISSUE TITLE
Create cert for host with port doesn't allow

### ISSUE THREAD

**Issue by truongnmt** [FiloSottile/mkcert#234]
I want to create a certification for a host with a specific port:

```bash
mkcert "localhost:4447"
```

On execute this following command, we get this following result:
```
Using the local CA at "/Users/truongnmt/Library/Application Support/mkcert" ✨
ERROR: "localhost:4447" is not a valid hostname, IP, URL or email
```

**Comment by arafel** [comment]
Hi

You can't include a port in the name - [this support doc](https://support.dnsimple.com/articles/what-is-common-name/) explains it quite well. To quote:

> The common name is not a URL. It doesn’t include any protocol (e.g. http:// or https://), port number, or pathname.

**Comment by truongnmt** [comment]
Thanks for pointing out!
