### ISSUE TITLE
Your connection is not private

### ISSUE THREAD

**Issue by protonwebmaster** [FiloSottile/mkcert#237]
Not working : NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by revathskumar** [comment]
I got this error when I tried to create certificate for `*.local` domain. 
mkcert is already providing a  warning for this. 

`Warning: many browsers don't support second-level wildcards like "*.local"`

I regenerated again without `*.local` and this error went away.

**Comment by FiloSottile** [comment]
That's indeed the only case I'm aware of, if anyone encounters the error in other cases, please provide more details in a new issue.
