### ISSUE TITLE
How to get the certs on Android?

### ISSUE THREAD

**Issue by ibes** [FiloSottile/mkcert#24]
Hi there,

sounds like an awesome tool. 
I fiddled around with CA and local certs one or two weeks ago and kind of got it working but it was a lot of work to do - you tool seems to be so much easier. 

But what I didn't manage was to get the cert accepted on my Android device so I can do local testing there. 
(Website on my computer, open to be seen from the network through IP address but via HTTPS -> needs to have an accepted cert). 
As far as I got this right, I could put the CA on my Android device and that should work. But how?

Do you have ideas for that?

**Comment by FiloSottile** [comment]
I added some instructions to the README. It's not exactly easy, but I don't think mkcert can do much to help. Let me know otherwise.

**Comment by sweetsour5** [comment]
Thank u
