### ISSUE TITLE
Safari will start limiting validity to 1 year

### ISSUE THREAD

**Issue by rfay** [FiloSottile/mkcert#241]
Per https://www.thesslstore.com/blog/ssl-certificate-validity-will-be-limited-to-one-year-by-apples-safari-browser/ Safari will start limiting cert validity to a year. 

I'd be in favor of switching mkcert certs to just have a 364-day validity. At least the way we use them, they get regenerated much sooner than a year.

**Comment by FiloSottile** [comment]
The one year limit only applies to public CAs, so it does not affect us.

> This change will not affect certificates issued from user-added or administrator-added Root CAs.

https://support.apple.com/en-us/HT211025
