### ISSUE TITLE
libnssutil3 was not loaded for installing

### ISSUE THREAD

**Issue by dakiesse** [FiloSottile/mkcert#246]
I've tried to execute `$ mkcert -install`

```
Using the local CA at "/Users/someuser/Library/Application Support/mkcert" ✨
The local CA is already installed in the system trust store! 👍
ERROR: failed to execute "certutil -A -d sql:/Users/someuser/Library/Application Support/Firefox/Profiles/2ekfser2.default-release": signal: abort trap

dyld: Library not loaded: /usr/local/Cellar/nss/3.36.1/lib/libnssutil3.dylib
  Referenced from: /usr/local/bin/certutil
  Reason: image not found
```
After that I've tried to execute `$ mkcert 0.0.0.0`

```
Using the local CA at "/Users/dakiesse/Library/Application Support/mkcert" ✨
Warning: the local CA is not installed in the Firefox trust store! ⚠️
Run "mkcert -install" to avoid verification errors ‼️

Created a new certificate valid for the following names 📜
 - "0.0.0.0"

The certificate is at "./0.0.0.0.pem" and the key at "./0.0.0.0-key.pem" ✅
```

MacOS: 10.15.2
I've tried to use `$ brew upgrade` but it didn't help me

**Comment by rfay** [comment]
I had a similar homebrew problem with osslsigncode, see https://github.com/mtrojnar/osslsigncode/issues/26 - in that case I was able to fix it with `brew link libgsf glib pcre`, not sure if that's relevant for you.

**Comment by FiloSottile** [comment]
This does not look like a mkcert issue: I assume the problem will be the same if you try to run `certutil` directly. You can try your luck with the Homebrew issue tracker, or maybe `brew reinstall nss` will help.
