### ISSUE TITLE
Where the .keystore is located? 

### ISSUE THREAD

**Issue by Urahara** [FiloSottile/mkcert#251]
Or is even possible to generate this type of certificate? I using jboss and i need the .keystore file, mkcert generate them too?

Example of my config:

 ```xml
   <Connector port="8443" protocol="HTTP/1.1" SSLEnabled="true" maxThreads="200" scheme="https" secure="true" clientAuth="false" sslProtocols="TLSv1,TLSv1.1,TLSv1.2" 
              keystoreFile="/root/.keystore" keystorePass="password <!-- code ommited -->
```

**Comment by FiloSottile** [comment]
I think the `keystoreFile` might be a PKCS#12 file, which you can generate with `mkcert -pkcs12`. The password is always `changeme` for compatibility reasons.

**Comment by ThePresence** [comment]
@FiloSottile Can we change the password later using mkcert?
