### ISSUE TITLE
net::ERR_SSL_KEY_USAGE_INCOMPATIBLE

### ISSUE THREAD

**Issue by romanpastu** [FiloSottile/mkcert#253]
When trying to make a Post request to localhost using chrome with axios in React, (Windows) I receive the above error.

When trying to make the same Post with postman, it works fine

**Comment by kaleidawave** [comment]
Also having this issue:
![image](https://user-images.githubusercontent.com/26967284/95678506-05480180-0bc5-11eb-868f-36eef0e6c520.png)

**Comment by deidyomega** [comment]
Im having the same issue

We are to use rootCA.pem on the server right?

**Comment by FiloSottile** [comment]
If you are seeing this error, it means you are trying to use the root CA directly. You are NOT supposed to use `rootCA.pem` directly. Instead, generate a certificate for `localhost` or `example.com` with `mkcert localhost` or `mkcert example.com` and use that.
