### ISSUE TITLE
Your connection to this site is not fully secure

### ISSUE THREAD

**Issue by likaiwalkman** [FiloSottile/mkcert#255]
![image](https://user-images.githubusercontent.com/4601453/79528339-4ccd5500-809c-11ea-964f-adf3233fe8e2.png)

**Comment by andresilva96** [comment]
The same issue on Chrome/81.0.4044.122, I'm using Linux.

**Comment by qWici** [comment]
Same. In Firefox works fine.
Browser: Chrome/81.0.4044.122
OS: Ubuntu 20.04 (few days ago on 18.04 works good)

**Comment by qWici** [comment]
@andresilva96 @likaiwalkman you can enable [allow-insecure-localhost flag](chrome://flags/#allow-insecure-localhost) for temp solution in dev.

**Comment by FiloSottile** [comment]
If the error says "outdated security configuration" the issue is not the certificate generated by mkcert, but some other TLS configuration detail of the HTTPS server.
