### ISSUE TITLE
ERR_CERT_AUTHORITY

### ISSUE THREAD

**Issue by catur515** [FiloSottile/mkcert#256]
I use nodejs on windows, when accessed from the desktop there are no problems.
![image](https://user-images.githubusercontent.com/22145610/79546807-38e61b00-80bd-11ea-8071-d105c0362ef5.png)

But when accessed from android. "Your Connection is not Private" ERR_CERT_AUTHORITY_INVALID
![image](https://user-images.githubusercontent.com/22145610/79547001-84002e00-80bd-11ea-95ed-156301153e77.png)

Then I try to check at https://www.ssllabs.com/ssltest

the results are as follows:
![image](https://user-images.githubusercontent.com/22145610/79546359-80b87280-80bc-11ea-84d6-2e1809152823.png)
![image](https://user-images.githubusercontent.com/22145610/79546439-a5ace580-80bc-11ea-8dbc-010776dd4272.png)

**Comment by andresilva96** [comment]
The same issue on Chrome/81.0.4044.122, I'm using Linux.

**Comment by FiloSottile** [comment]
mkcert certificates are NOT production certificates, so they will never work with third-party clients like SSL Labs. For production certificates look at Let's Encrypt.

For mkcert to work, you need to install the root on the device. For Android devices, see https://github.com/FiloSottile/mkcert#mobile-devices
