### ISSUE TITLE
Please clarify what does "Firefox support is not available on your platform" mean

### ISSUE THREAD

**Issue by TomasHubelbauer** [FiloSottile/mkcert#266]
Hello, I see the mention of the Firefox root store only being supported on macOS and Linux, not on Windows. I _think_ the above warning printed during `mkcert -install` refers only to the certificate root being placed to the Firefox root store, not mkcert on Windows not being able to generate Firefox compatible certificates, correct?

And if so, would https://gist.github.com/cecilemuller/9492b848eb8fe46d462abeb26656c4f8#windows-10-firefox be an alternative manual approach to installing the certificate root to the Firefox root store since the automated approach is not supported on Windows?

If that's the case, would you accept a PR which changes the warning text to instead list steps for the manual installation? In my opinion, a tool such as this, likely to be used by novice (as far as web certificates go) users such as myself could do a lot of good by hand-holding the users through the bits it cannot do for them automatically.

**Comment by TomasHubelbauer** [comment]
I've verified that the instructions in the linked Gist work for installing the CA to the Firefox root store. I have also checked out `main.go` to see where the warning text could be changed to print this information, but it looks like the message is more general than I thought, not Firefox specific, there needs to be a condition for detecting Firefox, first, if this is to be included:

https://github.com/FiloSottile/mkcert/blob/master/main.go#L281

I don't use Go so I wouldn't be able to test it so I retract my offer to prepare a PR for this. Hopefully this issue existing with the warning message in the title will lead people to Firefox instructions in the linked Gist instead, should there be more people like me who need it.

**Comment by francwalter** [comment]
> ... And if so, would https://gist.github.com/cecilemuller/9492b848eb8fe46d462abeb26656c4f8#windows-10-firefox be an alternative manual approach to installing the certificate root to the Firefox root store since the automated approach is not supported on Windows?
> ...

Thank for the link, especially the setting 

**security.enterprise_roots.enabled true**

helped me immediately :)
