### ISSUE TITLE
Create certificate with multiple Subject Alternative Names from file

### ISSUE THREAD

**Issue by antwal** [FiloSottile/mkcert#269]
Hi,

would it be possible to load the list of names directly from a text file?

i tried this way but it generates an error:

```
mkcert $(cat /etc/hosts | sed '/#/d' | awk '{ print $2 }' | tr "\n" " ")
-bash: /usr/bin/mkcert: Argument list too long
```

Thanks.

**Comment by FiloSottile** [comment]
That's... a lot of names. Maybe consider using a wildcard? This feature request never came up before, and can be handled like you did for shorter lists, so I'd rather not add a flag, sorry.
