### ISSUE TITLE
Unclear instruction - what to do?

### ISSUE THREAD

**Issue by WrongBit** [FiloSottile/mkcert#272]
Hi! I work on Win7x64. Under admin I run `mkcert -install`. All I got is just `rootCA-key.pem` and `rootCA.pem` in `c:\Users\itshim\AppData\Local\mkcert`. How these files will work if they just lie in a folder? I tried to search new certificate in Windows storage, but nothing. `Personal`, `Trusted Root Certification Authorities`, `Trusted Publishers`, `Third-Party Root Certification Authorities` - nobody has new certificate (despite Windows said it imports certificate). Hell, I even don't know what's the name of the certificate!

Can you please be more detailed what and where is stored? I try to make web server, but browser cannot establish `https` because no certificate.

**Comment by FiloSottile** [comment]
`mkcert -install` is just the installation step, then you can generate certificates to use with your web server with `mkcert example.com` or `mkcert localhost` etc.

See the README for some examples.
