### ISSUE TITLE
Firefox not working

### ISSUE THREAD

**Issue by ssuess** [FiloSottile/mkcert#275]
All other browsers on my system work, but Firefox steadfastly refuses to. I have verified the following:
1. nss is installed (and was when I generated the certs a month ago)
2. The root CA was in the trusted authorities perms of Firefox (and I have uninstalled/reinstalled serveral times to no avail)
3. Chrome, Safari, Edge all work fine
4. I am on Mac OS 10.5.5
5. My Firefox version is 78.0.1 (64-bit)
6. Root CA is trusted in my login and system keychain

Error message given is:

    Secure Connection Failed

    An error occurred during a connection to stephen.xxxx.xxxx.net. PR_CONNECT_RESET_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

I have tried everything I can think of, any suggestions?

**Comment by FiloSottile** [comment]
Hmm, what happens if you use the same certificate but a different server / TLS stack?

**Comment by ssuess** [comment]
Well, I finally figured out what the problem is, but still don't understand why this only affects Firefox: I am routing my traffic through a proxy (using mac app proxifier and an ssh SOCKS5 tunnel over port 9999). If I stop routing FF through the tunnel, it will correctly load my site. What is odd is that this same proxy setup works just fine for all other browsers to load the cert and my site.

**Comment by FiloSottile** [comment]
Maybe FF is using a different proxy protocol, or maybe its TLS stack does something different that the proxy doesn't like. The proxy might also be trying to verify the certificate if FF is not using TLS 1.3.

I think this is not something that mkcert can do anything about, but let us know if that's not the case!

**Comment by ssuess** [comment]
In case anyone else is having this problem, I discovered a workaround. Instead of using my system wide proxy router (proxifier), I can use the built in Firefox proxy settings, and then add an exception for my mkcert local site ("no proxy for" list in the same "Network Settings/Connection Settings" area of Firefox.)
