### ISSUE TITLE
ERROR: failed to execute "certutil -A": exit status 255

### ISSUE THREAD

**Issue by Cui-y** [FiloSottile/mkcert#28]
I follow the document steps.
The first step: mkcert -install

Created a new local CA at "/Users/**/Library/Application Support/mkcert" 💥
Password: ******

But it's wrong.
Error INFO:
ERROR: failed to execute "certutil -A": exit status 255
certutil: function failed: SEC_ERROR_LEGACY_DATABASE: The certificate/key database is in an old, unsupported format.

I don't know what to do
Ask for help, please!

**Comment by Cui-y** [comment]
![image](https://user-images.githubusercontent.com/21211512/42207732-3516008c-7edd-11e8-9ab0-a71b9a7cbc6c.png)

**Comment by thesyncim** [comment]
duplicated #12

**Comment by Cui-y** [comment]
@thesyncim  thanks a lot!

**Comment by Kawaiichanbest** [comment]
mkcert command not found?
