### ISSUE TITLE
Azure DevOps Pipelines: Installing local CA via PowerShell hangs

### ISSUE THREAD

**Issue by fenton-nick** [FiloSottile/mkcert#286]
I've installed mkcert in an Azure Pipeline windows VM via Chocolatey. However, installing the local CA via PowerShell hangs. I can't find anything significant in the logs for this pipeline task. I have to manually cancel the run after about 5 minutes.

```
mkcert -install
Created a new local CA at "/home/circleci/.local/share/mkcert" 💥 <--- agent hangs right here
```

**Comment by fenton-nick** [comment]
Could this be caused by the security warning the pops up when install a the cert for the CA? 

![image](https://user-images.githubusercontent.com/4750903/91107045-50707a00-e642-11ea-8906-7f2c7900bf59.png)

**Comment by fenton-nick** [comment]
Unfortunately, I had to go with a pure PowerShell (New-SelfsignedCertificate) approach in order to make integration tests run in CI.

**Comment by FiloSottile** [comment]
Yeah, I don't know of any way to avoid the warning when running `-install`. Does your PowerShell approach install a system root or just generate a certificate? If the latter, you can just skip `-install` and use mkcert. If the former, I am curious how it bypasses the dialog.

**Comment by fenton-nick** [comment]
It does install a Root CA certificate.

**Comment by kaylumah** [comment]
@fenton-nick can you share your script?
