### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by gabrielcalderon** [FiloSottile/mkcert#300]
* There's several pull request pending. Some very useful for common issues with this tool.
* There hasn't been a commit since March, 2020.

@FiloSottile any input?

**Comment by rfay** [comment]
I have attempted to contact @FiloSottile via twitter as well, with no response Unfortunately we had to fork the project to get arm64 releases, but it's not what we want to do. This is a good project in a good place by a brilliant contributor.

@FiloSottile it would be lovely if you'd let one of us help maintain it, or come back! We know you're busy, but come back!

**Comment by FiloSottile** [comment]
Hi folks, sorry about the long wait! I do have limited time for working on mkcert, but I also think the tool is more or less finished, in that it does what it's supposed to do, and I don't think most feature requests are in scope, so low commit traffic is to be expected.

I do plan to keep mkcert maintained, though! I'll always keep it up to date with browser and platform changes, so it does not stop working, and I'm happy to merge the occasional minor change.

I am doing a pass through the issues and the PRs today, so you should see movement on things like arm64 releases. I also plan to break out truststore support into an importable module, as that was a common request.

@rfay I wish I could give you Editor access to the issue tracker, but GitHub doesn't have such fine-grained access control for personal repositories :( I do appreciate the help in responding to issues quicker and more often than I manage to!
