### ISSUE TITLE
Remove codeSigning EKU?

### ISSUE THREAD

**Issue by FiloSottile** [FiloSottile/mkcert#303]
@mastahyeti @btoews can you help me remember why in #152 we added the codeSigning EKU when there is an email SAN? How are those related?

https://github.com/FiloSottile/mkcert/blob/a2b1208e9c7d6a9588bce49729cfedbdf9f8be21/cert.go#L96-L98

**Comment by btoews** [comment]
I had been using mkcert while I was developing
https://github.com/github/smimesign. I don’t recall if Github’s commit
signature checking requires the code signing EKU. @ptoomey3 could check
maybe. Regardless, I don’t need the EKU myself any longer, but it might be
useful to someone doing some kind of Git signing with mkcert.

**Comment by ptoomey3** [comment]
I'll try pushing up a quick change to see what happens if we mint a cert for SMIME signatures without that extension.

**Comment by ptoomey3** [comment]
Nothing in CI broke when I disabled adding this extension for certs used for SMIME signatures in our tests.

**Comment by FiloSottile** [comment]
Awesome, thank you for checking!
