### ISSUE TITLE
macOS Big Sur

### ISSUE THREAD

**Issue by jarretmoses** [FiloSottile/mkcert#305]
Apologize while not an issue I wanted to just bring this up. Is there a plan / has there been to test this package on the latest macOS beta for Big Sur? I only ask cause I know there were some issues with Catalina when it first came out off the bat and would love to know if it works with the next update out of the gate or not.

**Comment by rfay** [comment]
We've been running mkcert on Big Sur betas in our CI environment without trouble. Big Sur does seem to introduce more "need permission to access" some location, but other than that doesn't seem to have more trouble.

**Comment by FiloSottile** [comment]
I have read that "security add-trusted-cert" now shows a permission box even if run with sudo. I have not checked myself yet but I have a machine on the beta and will do soon.

**Comment by jarretmoses** [comment]
@rfay @filippobuletto thanks a lot for the response! Good to know.

**Comment by filippobuletto** [comment]
@jarretmoses you probably wanted to tag @FiloSottile !

**Comment by jarretmoses** [comment]
@filippobuletto yup sorry about that.

**Comment by FiloSottile** [comment]
Yep, tested with a fresh Big Sur and there's two of these dialogs which I doubt we can do anything about, but otherwise everything works.

![image](https://user-images.githubusercontent.com/1225294/100516137-08ea1480-3182-11eb-9120-781081e36b75.png)
