### ISSUE TITLE
choco install mkcert failed

### ISSUE THREAD

**Issue by Brolly0204** [FiloSottile/mkcert#308]
Failures
 - mkcert - mkcert not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

**Comment by rfay** [comment]
You either hit a glitch on Chocolatey or there's something wrong with your system. Here's what I see:

```
PS C:\WINDOWS\system32> choco install -y mkcert
Chocolatey v0.10.15
Installing the following packages:
mkcert
By installing you accept licenses for the packages.

mkcert v1.4.2 [Approved]
mkcert package files install completed. Performing other installation steps.
 ShimGen has successfully created a shim for mkcert.exe
 The install of mkcert was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.
```

I recommend uninstalling and reinstalling mkcert; consider reinstalling chocolatey if this continues. But everything is working fine.

**Comment by FiloSottile** [comment]
Thanks @rfay for checking. If the issue persists @Brolly0204 you might want to open an issue with Chocolatey, we don't manage that package directly.
