### ISSUE TITLE
Allow a custom comment in any generated names

### ISSUE THREAD

**Issue by vrillusions** [FiloSottile/mkcert#31]
I understand wanting to keep `mkcert development CA` in the name so no shenanigans like `Some Big Name Legit Authority CA` but it would be useful to add a _comment_ similar to the process of setting up a GPG key.  It asks for your Name, Email, and an Optional comment.  In GPG world it's so you could have `John Doe (Work Correspondence Only) <worker@example.com>`.

For here it would be to differentiate my `mkcert development CA` from someone else's `mkcert development CA`.  Yes, the serial numbers will be different but at glance see a certificate was issued by (don't think you can have parenthesis in a subject name) `mkcert development CA  - vrillusions dev work` or similar would be useful.

User experience could be something similar to GPG process where the `mkcert development CA` is hardcoded then prompt for an optional comment.

**Comment by FiloSottile** [comment]
Without going into custom comments like GPG which never felt like a good experience to me, would $USER@$HOSTNAME to the subject work?
