### ISSUE TITLE
Certificate issue in iOS 14

### ISSUE THREAD

**Issue by starostin** [FiloSottile/mkcert#312]
Hi. I am using mkcert and it works great on my mac. Also it worked fine on the iOS 13. But on 14 iOS I have an issue
![IMG_5475](https://user-images.githubusercontent.com/5508598/99908701-b7a6d480-2cec-11eb-8534-5d8e411f2f9a.PNG)
I have done all steps from the readme. But still no success. What could be wrong?

**Comment by FiloSottile** [comment]
This is not a certificate issue. The problem is that the TLS server implementation you are using does not support TLS 1.2 which is now required by iOS.

**Comment by starostin** [comment]
Oh, thanks a lot. I did not know that. You saved me a lot of time
