### ISSUE TITLE
[feature request] support loading encrypted private keys

### ISSUE THREAD

**Issue by lopezator** [FiloSottile/mkcert#315]
I'm not only using mkcert to generate & load certificates but also to load certificates from 3rd parties.

When trying to load one that has encription I get this error:

> ERROR: failed to parse the CA key: asn1: structure error: length too larg

Is related with this issue?

https://github.com/golang/go/issues/18692

I'm not into certificates, crypto, etc.. so sorry if this is a silly request/issue.

Thank you for this awesome tool @FiloSottile !

**Comment by FiloSottile** [comment]
Hi! Replacing the mkcert CA is not really supported. I am glad it works for you, but it's not something we'll introduce extra complexity to make work in more cases. mkcert generates those files, and expects them to look like the files it generates. In your case, you might be able to make it work by decrypting the key with openssl in advance, but no promises!

**Comment by lopezator** [comment]
Thanks for your response @FiloSottile !!

I completely understand.

Best.
