### ISSUE TITLE
Cannot sign csr get panic error

### ISSUE THREAD

**Issue by symgryph** [FiloSottile/mkcert#318]
I generated a csr on an appliance I use, and when I use the following:

```
mkcert -csr my.test.csr
```

I get:

```

goroutine 1 [running]:
main.(*mkcert).fileNames(0xc000155f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x121fc40, 0xc000066300, 0xc00042c000, 0x46b)
	/private/tmp/mkcert-20201126-82459-i1bflq/mkcert-1.4.3/src/github.com/FiloSottile/mkcert/cert.go:177 +0x3cc
main.(*mkcert).makeCertFromCSR(0xc000155f00)
	/private/tmp/mkcert-20201126-82459-i1bflq/mkcert-1.4.3/src/github.com/FiloSottile/mkcert/cert.go:266 +0x7c8
main.(*mkcert).Run(0xc000155f00, 0xc0000121d0, 0x0, 0x0)
	/private/tmp/mkcert-20201126-82459-i1bflq/mkcert-1.4.3/src/github.com/FiloSottile/mkcert/main.go:203 +0x64a
main.main()
	/private/tmp/mkcert-20201126-82459-i1bflq/mkcert-1.4.3/src/github.com/FiloSottile/mkcert/main.go:145 +0x851
```

**Comment by Vaka82** [comment]
Same issue - Any suggestions..?

**Comment by Vaka82** [comment]
It's panicking @ the below code as hosts slice is empty - 

![image](https://user-images.githubusercontent.com/3131980/101522389-be6c5300-394c-11eb-90ff-1a8405412894.png)

Adding this before that fileNames call seem to fix this issue for me.

**if len(hosts) == 0 {
		hosts = []string{csr.Subject.CommonName}
	}**
	
	certFile, _, _ := m.fileNames(hosts)

**Comment by gergelyzs** [comment]
i have found the same issue. I believe it is because the CSR has no SAN. If you can modify your CSR, it's easy enough, I having no SAN is deprecated. For me, the CSR is coming from an old iDRAC, so no way I can change it.

Fix works because it reads the CN. @Vaka82 care to make a PR?

**Comment by adippel** [comment]
+1 encountered this just recently. dont know if using CN is the right way since using CN for domain names is not the right way. At least replacing the meaningless panic is a must.

**Comment by FiloSottile** [comment]
Fixed, thank you for the report. The feature to use the CN if there were no SANs was already there, but then it was trying to print the hosts from the CSR instead of the generated certificate.
