### ISSUE TITLE
failed to execute "security add-trusted-cert"

### ISSUE THREAD

**Issue by eni9889** [FiloSottile/mkcert#322]
I am running 

```
mkcert -install
```

under rosetta 2 on an M1 and em getting this output:

```
Sudo password:
ERROR: failed to execute "security add-trusted-cert": exit status 1

SecTrustSettingsSetTrustSettings: One or more parameters passed to a function were not valid.
```

**Comment by FiloSottile** [comment]
I can't reproduce this. `mkcert -install` works for me under Rosetta 2 on a M1 in macOS 11.2.

Can you provide more details?

**Comment by rfay** [comment]
@eni9889 some time has passed since your original post, and in the meantime M1 homebrew has started supporting most things, so I recommend getting rid of any homebrew you may have installed and then installing M1 homebrew (it goes in /opt/homebrew) and then installing the *Apple Silicon* mkcert with `brew install mkcert` and try that. 

I have no trouble with any version of mkcert in M1, but this is the one to use right now.

**Comment by timsutton** [comment]
Does this work in a fully-automated manner on the M1? One of the major security-related changes in Big Sur was to no longer allow fully-automated root certs trusting. In the [release notes](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes)

```
Security
New Features
macOS Big Sur 11 beta improves system security by requiring an administrator password when a certificate trust settings change is made in the admin trust domain. Running as the root user alone is no longer sufficient to modify certificate trust. User trust domain settings continue to require confirmation by entering the password for the user’s account. This change may affect you if one of the following is true:

You have written scripts which call /usr/bin/security add-trusted-cert -d ... as root.

Your process runs as root and calls the SecTrustSettingsSetTrustSettings function to trust a certificate.

Workflows that add trust settings in the admin trust domain, such as for an enterprise root certificate, may require modification if the user can’t authenticate as an administrator at the time settings are changed. (21855995)

Workaround: Use Apple Configurator 2 to create and install a configuration profile containing your root certificate.
```

**Comment by rfay** [comment]
We use mkcert in ddev just fine on the mac M1, just like every other place. It's available via homebrew on the mac M1 as well.

**Comment by rfay** [comment]
I was able to solve this on Github Actions CI using `sudo security authorizationdb write com.apple.trust-settings.admin allow`

Found this answer in https://github.com/actions/virtual-environments/issues/4519#issuecomment-970202641

**Comment by fouss** [comment]
same issue here, any update ?

**Comment by FiloSottile** [comment]
Duplicate of #415. Thank you for finding the release notes about it.
