### ISSUE TITLE
import cycle not allowed

### ISSUE THREAD

**Issue by hippolee** [FiloSottile/mkcert#323]
I tried to build from source, used cmd in readme says

git clone https://github.com/FiloSottile/mkcert && cd mkcert
go build -ldflags "-X main.Version=$(git describe --tags)"

then
import cycle not allowed
package .
	imports bytes
	imports errors
	imports internal/reflectlite
	imports internal/unsafeheader
	imports runtime
	imports internal/bytealg
	imports internal/cpu
	imports runtime

What should I do?
my go version is ”go version go1.9.4 linux/amd64“

**Comment by FiloSottile** [comment]
Sorry, but Go 1.9 has been unsupported for years. It also looks like your installation is somehow corrupt.

If you install a recent version of Go from https://golang.org/download then mkcert should build correctly.
