### ISSUE TITLE
Can i specify the expiration date instead of 2 years 3 month?

### ISSUE THREAD

**Issue by bestplay** [FiloSottile/mkcert#324]
https://github.com/FiloSottile/mkcert/blob/1a5aaff12e0edb54f32ce187079d05c4a1ffd19b/cert.go#L62

I need more longer expiration time for self signed certs, not only for IOS/MAC.

**Comment by FiloSottile** [comment]
Sorry, but mkcert is an opinionated tool that aims to hide all the complexity it can from developers, not a general purpose local CA management tool. We're not going to make the lifetime configurable when that can make the certificates mysteriously fail on some platforms.

**Comment by BenjaminNolan** [comment]
So, Apple changed their security policies in April 2021 after this ticket was closed, and the new policies reject any certificates over a year in expiration without certain other requirements attached to them. I appreciate this is an opinionate tool, however the ability to generate a temporary certificate with a 3-6 month length would be very useful for people developing on macOS versions >= 10.14. https://sslmate.com/blog/post/apples_new_ct_policy has an explanation of exactly what they changed in it, which I'm hoping means more to you than me (SSL's internals isn't really in my wheelhouse!)

**Comment by ruan11223344** [comment]
i think you can modify this line . then recompile and generate binaries to replace the original binaries
![image](https://github.com/FiloSottile/mkcert/assets/5679023/f1085929-1be3-4194-9808-2a855728039b)

**Comment by xinnjie** [comment]
> So, Apple changed their security policies in April 2021 after this ticket was closed, and the new policies reject any certificates over a year in expiration without certain other requirements attached to them. I appreciate this is an opinionate tool, however the ability to generate a temporary certificate with a 3-6 month length would be very useful for people developing on macOS versions >= 10.14. https://sslmate.com/blog/post/apples_new_ct_policy has an explanation of exactly what they changed in it, which I'm hoping means more to you than me (SSL's internals isn't really in my wheelhouse!)

Until today 2025/2/1, root certificate (validate for 10 years) produced by mkcert is still usable on IPhone. Though Apple seems to add an extra step. We need to trust the certicate in `Certificate Trust Setting`.

So for this mac/ios use case, specifying expiration date is still not needed. @BenjaminNolan
