### ISSUE TITLE
Firefox can't print cibc bank statement

### ISSUE THREAD

**Issue by ThomasJohn975** [FiloSottile/mkcert#328]
Firefox can't print CIBC bank statement. (Bank statement only print total three pages) . First and last pages are half blank. this same pages only see in print preview. Simplify pages get more pages. chrome, IE,Edge and safari works fine. All utility and bank statements other bills have to see properly in browser. Firefox print coding needs to improve with print preview like chrome.

**Comment by FiloSottile** [comment]
Sorry, but this doesn't seem like an issue related to the mkcert project.
