### ISSUE TITLE
Build mkcert release for Apple Silicon

### ISSUE THREAD

**Issue by rfay** [FiloSottile/mkcert#329]
I note that you already have mkcert in homebrew for Apple Silicon... Could we also have it built here in releases?

**Comment by FiloSottile** [comment]
That would require building releases with Go 1.16, so I'll wait for the release candidate and switch.

**Comment by rfay** [comment]
Thanks, that will be fine. As you know, the beta1 is out there and easy enough to use. But release candidate will work out fine.
