### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID on Raspbian Buster

### ISSUE THREAD

**Issue by sguilliard** [FiloSottile/mkcert#334]
Been following the directions to install on Raspberry Pi 4b here: [https://kifarunix.com/how-to-create-self-signed-ssl-certificate-with-mkcert-on-ubuntu-18-04/](url) (using the latest releases - tried both [mkcert-v1.4.3-linux-arm64](https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-arm64) wouldn't execute, but the 32-bit version executed ok: [mkcert-v1.4.3-linux-arm](https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-arm)
mkcert appears to be installed ok, but the CA isn't being accepted by the Chromium browser on the local machine (should this also work for other machine accessing from the LAN?). Trying to find more details directions to see if there's soemthing I've missed, but now at a loss...

Browser returns the following in Chrome (Firefox the same):
```
NET::ERR_CERT_AUTHORITY_INVALID
Subject: mkcert development certificate

Issuer: mkcert root@aardvarkyweb

Expires on: 24 Apr 2023

Current date: 24 Jan 2021

PEM encoded chain:
```

**Comment by FiloSottile** [comment]
mkcert needs to be installed on the machine from which you access the site. If you install it on a Raspberry Pi, you then need to follow there instructions to copy its CA to your computer and install it.

https://github.com/FiloSottile/mkcert#installing-the-ca-on-other-systems

**Comment by sguilliard** [comment]
The error is from the local machine (the same machine that mkcert is installed on)

**Comment by sguilliard** [comment]
I think I've solved the problem. Install should not be done from the root on a raspberry pi (do not use SUDO), and neither should the cert generation. Is this a thing just on the RPi? Anyway, all working now...

**Comment by FiloSottile** [comment]
Glad you got it working. mkcert will generate a different CA for every user you run it as, so root will have a different CA.
