### ISSUE TITLE
Issue with Zoom after running mkcert

### ISSUE THREAD

**Issue by oreillygshane** [FiloSottile/mkcert#336]
After running mkcert to install localhost certs , I am now getting this Zoom popup macOS 11.2, which continues to appear no matter what I click:
<img width="467" alt="Screenshot 2021-02-03 at 09 50 36" src="https://user-images.githubusercontent.com/15385374/106773211-42477080-665a-11eb-994b-54a56a9889c4.png">

Any ideas? Thanks in advance!

**Comment by FiloSottile** [comment]
Hmm, installing mkcert itself should not (and does not on my machine) cause that. Did you also enable an intercepting proxy and configure it to use the mkcert root? That would explain the popup.

**Comment by oreillygshane** [comment]
That indeed would be the issue., makes sense.

Closing
