### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR : sent an invalid response

### ISSUE THREAD

**Issue by ProgrammingPlanet** [FiloSottile/mkcert#354]
I installed mkcert using choco in windows 10

Then I generated a certificate for linux.vm domain from windows 10 PowerShell (including mkcert -install command) and imported it in my virtual machine running apache2 server on the ubuntu 20.04 server edition.

when I visit **https://linux.vm** from chrome on windows 10, then it gives me ERR_SSL_PROTOCOL_ERROR (screenshot below)
although **http://linux.vm** working good.

![Screenshot (399)](https://user-images.githubusercontent.com/48400531/111026845-b4a63000-8412-11eb-984a-03bab259d4b4.png)

**Comment by FiloSottile** [comment]
This looks like an issue with the TLS/HTTPS server implementation, not with the certificate. mkcert only generates the certificate, and has no control over the server you load it into. Try updating the version or configuration of your TLS/HTTPS server.
