### ISSUE TITLE
How to install silently in Windows OS

### ISSUE THREAD

**Issue by andrew-wx** [FiloSottile/mkcert#358]
Hi：
Thanks for reading, because my English is not good.
This paper uses machine translation.

Due to the need of business development, executing "mkcert - install" in Windows system will prompt whether to install certificate or not. How to select "yes" installation by default

Thank！

**Comment by rfay** [comment]
The security warning is from Windows, not from mkcert. A [quick google](https://www.google.com/search?q=avoid+security+warning+when+installing+ca+on+windows&oq=avoid+security+warning+when+installing+ca+on+windows&aqs=chrome..69i57j33i160l4.7905j0j4&sourceid=chrome&ie=UTF-8) didn't find any good ways to go around it.

**Comment by andrew-wx** [comment]
Thank you. I use the. Net desktop program (WPF) and windows "user32. DLL" API to realize this function.
