### ISSUE TITLE
How to install pre-built binaries?

### ISSUE THREAD

**Issue by winternet-studio** [FiloSottile/mkcert#364]
How am I suppose to install the pre-built binaries from https://github.com/FiloSottile/mkcert/releases - they have no file extension and no description of how should be used!

(My goal is installing mkcert in a docker dev environment silently - which I couldn't figure out how to do with homebrew - which also took forever to install)

**Comment by juanuys** [comment]
If your container OS is Linux, copy https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64 to e.g. `/usr/local/bin/mkcert` inside the container.

**Comment by winternet-studio** [comment]
Ah, thanks. Would be good to mention that in the readme file!
