### ISSUE TITLE
giving filenames doesnt work

### ISSUE THREAD

**Issue by degoya** [FiloSottile/mkcert#375]
i've tried to use this command
mkcert localhost -key-file server.key -cert-file server.crt 127.0.0.1 192.168.40.59 192.168.178.51 192.168.178.21 web.local

The Output is

Created a new certificate valid for the following names 📜
 - "localhost"
 - "--key-file"
 - "server.key"
 - "--cert-file"
 - "server.crt"
 - "127.0.0.1"
 - "192.168.40.59"
 - "192.168.178.51"
 - "192.168.178.21"
 - "web.local"

The certificate is at "./localhost+9.pem" and the key at "./localhost+9-key.pem" ✅

the files are not named server.key und server.crt like expected.

i've tested on both debian and windows

**Comment by dennisbaum** [comment]
You must place the file-options options before the domain names list
