### ISSUE TITLE
install esdsa root ca not supported

### ISSUE THREAD

**Issue by beckend** [FiloSottile/mkcert#378]
installing by supplying `CAROOT` when the root CA is of type esdsa yields error:
```shell
ERROR: failed to read the CA key: unexpected content
```

**Comment by FiloSottile** [comment]
mkcert only supports roots it generated itself. This is intentional as it limits the maintenance cost. However, I'll work on extracting the truststore code into a library #45, so a more general-purpose CLI tool can be built on top of it.
