### ISSUE TITLE
Brew install mkcert fails

### ISSUE THREAD

**Issue by angeliquejw** [FiloSottile/mkcert#380]
Running `brew install mkcert` results in the following message:

```
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "mkcert"
Download failed: https://homebrew.bintray.com/bottles/mkcert-1.4.3.mojave.bottle.1.tar.gz
```

**Comment by rfay** [comment]
You need to update your homebrew. Homebrew stopped using bintray (and bintray shut down) a few months ago. Do a `brew update`

**Comment by angeliquejw** [comment]
Ack. Thank you so much, @rfay!
