### ISSUE TITLE
Upload mkcert to winget repository

### ISSUE THREAD

**Issue by zhanghua000** [FiloSottile/mkcert#400]
winget is now in active developing and has more and more packages. It will be more convenient to install on Windows if you can upload mkcert to its repository. Here is tutorial: https://github.com/microsoft/winget-pkgs#submitting-a-package. Thank you in advance.

**Comment by FiloSottile** [comment]
> Note: At this time installers must either be MSIX, MSI or .exe application installers. Standalone or portable executables, compressed .zip files, and fonts are not currently supported.

I would appreciate a PR to add a GitHub action that produces a suitable installer!

**Comment by 4n70w4** [comment]
HI! Any news?

**Comment by Barokai** [comment]
portable apps support is coming soon to winget, pre-release versions of 1.3 already contain it: https://github.com/microsoft/winget-cli/releases/tag/v1.3.2091
"Support for installation of portable/standalone apps https://github.com/microsoft/winget-cli/issues/182"

**Comment by goremykin** [comment]
Is this one official? I don't see any information about winget in readme so I am not sure
https://winget.run/pkg/FiloSottile/mkcert

**Comment by zhanghua000** [comment]
https://github.com/microsoft/winget-pkgs/tree/master/manifests/f/FiloSottile/mkcert/1.4.4
From the commit infomation I do not think it is official. But anyway there has already been a kindness contributor who achieved this, I think I can close this issue now.
