### ISSUE TITLE
Default behavior should be to do nothing

### ISSUE THREAD

**Issue by 89z** [FiloSottile/mkcert#401]
I just ran this tool with no arguments, expecting to just get a help screen. However it seems running without arguments actually does something:

~~~
PS C:\> mkcert-v1.4.3-windows-amd64
Created a new local CA 💥
Note: the local CA is not installed in the system trust store.
Run "mkcert -install" for certificates to be trusted automatically ⚠️
~~~

Can someone clarify what exactly the program does, if you run it with no arguments? I didnt see any files created in the local directory, so not sure.

**Comment by 89z** [comment]
Found it:

~~~
C:\Users\Steven\AppData\Local\mkcert
~~~

I dont like that. I will just repeat my initial comment, that I think the should should only be printing usage, if run without arguments, or at least if its going to create files, it should be telling the user where those files are located.

**Comment by rfay** [comment]
I agree, shouldn't do that. Just usage if no args.
