### ISSUE TITLE
Update Website link in Repository About section

### ISSUE THREAD

**Issue by mukeshgurpude** [FiloSottile/mkcert#402]
<img width="216" alt="image" src="https://user-images.githubusercontent.com/55982424/133915569-cc87654f-87d3-4af8-88e1-ab80a4246a00.png">

Current link(https://mkcert.dev) redirects back to this repository..
Update the link to actual homepage https://mkcert.org/

**Comment by FiloSottile** [comment]
mkcert.org is an unrelated project. mkcert.dev is the short link to reach this repository.
