### ISSUE TITLE
Cert not being reflected on localhost

### ISSUE THREAD

**Issue by yadavankit** [FiloSottile/mkcert#41]
`mkcert example.com '*.example.org' myapp.dev localhost 127.0.0.1 ::1`  creates the certificate and chain at `/Users/WARL0CK/Library/Application Support/mkcert` successfully.

`nginx` running at `localhost:80` doesn't reflect `https` on any browser, even after multiple cert builds and server restarts.

Am running this on `macOS High Sierra Version 10.13.5`.

**Comment by FiloSottile** [comment]
`mkcert -install` makes sure the mkcert certificates don't cause TLS trust errors. `mkcert localhost` creates the certificate and key (two `.pem` files) in the current directory. **It's up to you to install them into your HTTP server.** Also, 80 is the port for HTTP, so you'll have to use port 443 for HTTPS after installing the certificate.

**Comment by yadavankit** [comment]
That worked. Thanks 👍

**Comment by jonathanbossenger** [comment]
Sorry to comment on an old, closed ticket, but are there any good online resources you could recommend for how to install the certificates on a localhost Apache server running on Ubuntu?

**Comment by adamdecaf** [comment]
The apache config will look pretty similar to this: https://github.com/FiloSottile/mkcert/issues/56#issuecomment-417105075

**Comment by jonathanbossenger** [comment]
@adamdecaf thank you kindly sir.

**Comment by billp72** [comment]
Once I created files, I simply copied the localhost+1.pem and localhost+1-key.pem files to .localhost-ssl directory. I launched the app but I'm still getting insecure. Any advice? thanks
