### ISSUE TITLE
Advanced options aren't working

### ISSUE THREAD

**Issue by danilobatistaqueiroz** [FiloSottile/mkcert#411]
Some Advanced options don't work, for example, in none of these cases :  
`mkcert -pkcs12`  
or  
`mkcert -pkcs12 localhost.p12`  
or  
`mkcert -pkcs12 localhost.p12 localhost`

**Comment by FiloSottile** [comment]
Not enough information to understand if there is an issue in mkcert. Feel free to open a new issue if still encountering the problem.
