### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by klauern** [FiloSottile/mkcert#42]
I know it's mentioned in the [README](https://github.com/FiloSottile/mkcert#installation) that this support is coming soon, but I'd like to correlate it to an issue that can be tracked. :)

**Comment by sebdeckers** [comment]
Here is the Windows solution to entrust certificates in the OS store:
https://gitlab.com/sebdeckers/tls-keygen/blob/master/index.js#L202-224

Should be easy for someone to port this over to Golang.

Just found out about mkcert. Half a year ago I implemented a similar tool using Node.js for Mac/Lin/Win.

🗝 `tls-keygen`

- NPM: [tls-keygen](https://www.npmjs.com/package/tls-keygen)
- Code: [GitLab.com/sebdeckers/tls-keygen](https://gitlab.com/sebdeckers/tls-keygen)

**Comment by cretz** [comment]
Done, ref #46. I signed the CLA too.

**Comment by JacobDB** [comment]
Having this work with [WSL](https://docs.microsoft.com/en-us/windows/wsl/about), and not just CMD would be awesome. Not sure how that would work interfacing between the Linux environment and Windows though.

**Comment by adamdecaf** [comment]
Doesn't WSL (with Ubuntu) use the Ubuntu certificate store filepath? IIRC there was nothing windows specific when I tried it.

**Comment by cretz** [comment]
It all comes down to how it's compiled. If it's compiled with Linux Go in WSL, when run it will do the Linux thing. If it's compiled with Windows Go, it will do the Windows thing. Do in theory, due to the fact that WSL can execute Windows `.exe`s, you can have two `mkcert` executables callable in WSL, one that does a Linux thing and one that does a Windows thing :-)

**Comment by Geczy** [comment]
Any updaet

**Comment by 2PintChristianN** [comment]
Noticed that the binary is not signed on windows, which makes windows defender less than happy :/ Borderline bug in our situation.
