### ISSUE TITLE
is it safe to install a certificate generated by mkcert from other people?

### ISSUE THREAD

**Issue by dfang** [FiloSottile/mkcert#429]
what if i install a certificate generated by mkcert to my mac from xyz.com and trusted it?   is it safe?   can he (the man who generated the certificate) decrypt what i searched on https://www.google.com or what i bought on https://amazon.com?

**Comment by FiloSottile** [comment]
It is not safe to install a _root_ generated by mkcert ([this process](https://github.com/FiloSottile/mkcert#installing-the-ca-on-other-systems)). That will indeed allow them to intercept connections to any site.

Installing a specific site certificate (that generated by `mkcert example.com` for example) will only allow intercepting connections to that specific site.

**Comment by dfang** [comment]
very clear, thanks !
