### ISSUE TITLE
Assistance in building mkcert v1.0.0

### ISSUE THREAD

**Issue by NaiCity** [FiloSottile/mkcert#43]
Hello FiloSottile,

I'm trying to install mkcert on Ubuntu 18.04.  I have already  installed libnss3-tools and downloaded the mkcert tarball

apt install libnss3-tools

wget https://github.com/FiloSottile/mkcert/archive/v1.0.0.tar.gz

I'm not sure how to proceed from there. Kindly assist me. Thank you.

**Comment by FiloSottile** [comment]
Download the pre-built binary instead (https://github.com/FiloSottile/mkcert/releases/download/v1.0.0/mkcert-v1.0.0-linux-amd64), make it executable (chmod +x) and use it directly (./mkcert-...).

**Comment by NaiCity** [comment]
This is what I'm getting.

root@ip-172-31-44-56:/home/ubuntu# ./mkcert-v1.0.0-linux-amd64
Using the local CA at "/root/.local/share/mkcert" ✨
Warning: the local CA is not installed in the system trust store! ⚠️
Run "mkcert -install" to avoid verification errors ‼️

Usage:

        $ mkcert -install
        Install the local CA in the system trust store.

        $ mkcert example.org
        Generate "example.org.pem" and "example.org-key.pem".

        $ mkcert example.com myapp.dev localhost 127.0.0.1 ::1
        Generate "example.com+4.pem" and "example.com+4-key.pem".

        $ mkcert '*.example.com'
        Generate "_wildcard.example.com.pem" and
"_wildcard.example.com-key.pem".

        $ mkcert -uninstall
        Uninstall the local CA (but do not delete it).

Change the CA certificate and key storage location by setting $CAROOT,
print it with "mkcert -CAROOT".

**Comment by ninjamonz** [comment]
./mkcert-v1.0.0-linux-amd64 -install
./mkcert-v1.0.0-linux-amd64 example.org

**Comment by NaiCity** [comment]
Great, the commands run just fine. I have hosted an apache web server on
AWS and run the commands as indicated. The problem is that the web server
is still using http://ip-address instead of https://ip-address  Any clue as
to what I'm doing wrong?

**Comment by adamdecaf** [comment]
@NaiCity `mkcert` doesn't automagically setup your apache2 configs to use the certificate. You'll need to add that to your apache config. 

Here's an example: https://www.digicert.com/ssl-support/apache-multiple-ssl-certificates-using-sni.htm

**Comment by NaiCity** [comment]
Hey Filippo could you please give me a step by step guide on how to do this
I have tried configuring the apache config file but it doesn't work on my
side.

**Comment by FiloSottile** [comment]
I'm sorry, but I can't provide support for all the web server configurations.

mkcert will generate trusted certificates for you. You have to configure your web server to:

* use that cert and key
* listen on port 443 for HTTPS
* redirect from HTTP to HTTPS (if that's what you want)
* possibly change links and resource addresses (if needed)
