### ISSUE TITLE
Firefox 107 - SEC_ERROR_BAD_SIGNATURE

### ISSUE THREAD

**Issue by lumin888** [FiloSottile/mkcert#482]
## Environment

* Operating system (including version): Windows 10 Home 22H Build 19045.2251
* mkcert version (from `mkcert -version`): v1.4.4
* Server (where the certificate is loaded): XAMPP 8.6.1 localhost
* Client (e.g. browser, CLI tool, or script): Firefox 107

## What went wrong

Prior to Firefox 107, self sign certs generated by mkcert worked fine on my localhost installation.

After Firefox updated to 107, I get the following error:

> Secure Connection Failed

> An error occurred during a connection to localhost. Peer’s certificate has an invalid signature.

> Error code: SEC_ERROR_BAD_SIGNATURE

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Not sure if the updated Firefox changed something, but if anyone has any ideas, please let me know.

**Comment by spacexnasa** [comment]
same problem +1

**Comment by lumin888** [comment]
I had a chance to revisit this after having a weird issue with Firefox 111 and needed to clear all the application data. Anyway, it was still broken so I regenerated the cert using "mkcert localhost" and updated xammp's copy. Restarted apache and everything is working again. Closing as I don't think it's a mkcert issue.
