### ISSUE TITLE
Installing in Firefox failed... The local CA is now installed in the Firefox trust store...

### ISSUE THREAD

**Issue by leepeterson** [FiloSottile/mkcert#51]
I use Firefox Developer Edition. I also install apps in `$HOME/Applications`. I've symlinked `$HOME/Applications/Firefox Developer Edition.app` to `/Applications/Firefox.app` in an effort to possibly solve this mkcert issue. Perhaps I've solved it given the output I see:

```
→ mkcert -install
Using the local CA at "/Users/[user]/Library/Application Support/mkcert" ✨
Installing in Firefox failed. Please report the issue with details about your environment at https://github.com/FiloSottile/mkcert/issues/new 👎
Note that if you never started Firefox, you need to do that at least once.
The local CA is now installed in the Firefox trust store (requires browser restart)! 🦊

```

But I'm a bit confused about what's actually happened. "Using local CA... Firefox installation failed... local CA is now installed in Firefox..."

That said, I _have_ made good use of mkcert: system keychain trusts the root, certs are created for local vhosts, paths to ipv4 & ipv6 pem files are correctly set in Nginx conf files, browsers are validating the certs... but perhaps I'm taking the long way around it.

Any clarification would be greatly appreciated.

**Comment by FiloSottile** [comment]
@leepeterson I should have fixed both the missed detection of Firefox Developer Edition, and the misleading message, but I'm not sure if that will fix the root issue.

Can you try the latest master, and if it doesn't work report the output of `ls $HOME/Library/Application Support/Firefox/Profiles/`?

**Comment by FiloSottile** [comment]
Timeout in waiting for info state. Please reopen if the root issue is still present.
