### ISSUE TITLE
Module path should be canonical

### ISSUE THREAD

**Issue by jmooring** [FiloSottile/mkcert#528]
See <https://go.dev/ref/mod#module-path>.

Current:

```text
module filippo.io/mkcert
```

Should be:

```text
module github.com/FiloSottile/mkcert
```

Why?

```text
$ go install github.com/FiloSottile/mkcert@latest
go: github.com/FiloSottile/mkcert@latest: github.com/FiloSottile/mkcert@v1.4.4: parsing go.mod:
	module declares its path as: filippo.io/mkcert
	        but was required as: github.com/FiloSottile/mkcert
```

Yes, I know I can install with `go install filippo.io/mkcert@latest`, but that was not what I expected based on my experience installing  other Go programs.

**Comment by bep** [comment]
The big upside with "vanity paths" like module `filippo.io/mkcert` is that they are host agnostic (which is a great thing if you move your stuff from GitHub to GitLab or something) -- which in some sense makes them ... more canonical?

**Comment by jmooring** [comment]
I suppose this is really just a documentation issue, because you don't know the "more canonical" (vanity) import path until you've tried the "less canonical" import path.
