### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by bugnano** [FiloSottile/mkcert#548]
There are 33 open PRs, and the last development activity was more than 1 year ago.
Now, I understand that this project is mature, so it doesn't need much activity, but keeping PRs that could bring useful features open for months without acknowledging their existence makes me worry about the state of this project.

**Comment by gaby** [comment]
@bugnano This happens every year, check the related tickets below.

Ping @FiloSottile 

Related: https://github.com/FiloSottile/mkcert/issues/421 and https://github.com/FiloSottile/mkcert/issues/300

**Comment by awoimbee** [comment]
@FiloSottile IMO you should add other people as maintainers, that's how `xz` was compromised, but it's also how open-source projects stay alive and it's the best way to avoid maintainer burnout.

Damn, github even has a nice page about this <https://opensource.guide/maintaining-balance-for-open-source-maintainers/>.

**Comment by FiloSottile** [comment]
This project is still maintained. I monitor issues, and would respond promptly to security reports or any breakage that makes mkcert not work anymore for its current users. Issues and PRs that are about expanding the pool of users mkcert is useful for are not urgent, and I work on them in batches.

That's how I manage my maintainer workload, and it works fairly well for me and for my projects.

I've written this up and linked it from CONTRIBUTING to better set expectations. https://filippo.io/maintenance
