### ISSUE TITLE
Mkcert Certificates causes flutter cli tools to throw tls error

### ISSUE THREAD

**Issue by e-reifer** [FiloSottile/mkcert#549]
## Environment

* Operating system (including version): macOS Ventura 13.4.1
* mkcert version (from `mkcert -version`): v.1.4.4
* Server (where the certificate is loaded):
* Client (e.g. browser, CLI tool, or script): CLI (bin/bash)

## What went wrong

Mkcerts prohibits the flutter cli to be able to get packages as the terminal browser uses the system-wide certitifacate generated by mkcert. I have not found a way to disable this. 

`flutter doctor` shows this:
`
[!] Network resources
    ✗ A cryptographic error occurred while checking "https://pub.dev/":
      Handshake error in client
      You may be experiencing a man-in-the-middle attack, your network may be
      compromised, or you may have malware installed on your computer.
`

`flutter pub get` shows TLS error:

`Got TLS error trying to find package args at https://pub.dev`

Any help is appreciated

**Comment by e-reifer** [comment]
Could resolve it myself with the help of chatgpt. Mkcert was just a side effect. The real cause was me using dnsmasq service the unintentionally redirected all "pub.dev" results to localhost while using mkcert's certificate.

**Comment by coskuncay** [comment]
hi @e-reifer , so how did you solve it ?

**Comment by e-reifer** [comment]
I've Checked the dnsmasq.conf file `/opt/homebrew/etc/dnsmasq.conf` and deleted a line similar to `address=/.dev/127.0.0.1`
