### ISSUE TITLE
Basic commands don't work on macOS after brew install (mkcert -install, -CAROOT responds with "unknown option")

### ISSUE THREAD

**Issue by kopeboy** [FiloSottile/mkcert#557]
## Environment

* Operating system (including version): macOS Ventura 13.5.2
* mkcert version (from `mkcert -version`): 3.2.0
* Server (where the certificate is loaded): local
* Client (e.g. browser, CLI tool, or script): any

## What you did

1. brew uninstall --ignore-dependencies mkcert => ok
2. brew install mkcert => ok
3. mkcert -install => **error: unknown option**
4. mkcert -CAROOT => **error: unknown option**

## What went wrong
I don't know. Maybe multiple copies of go on my machine, or an installation in a non-canonical location, or a problem with the homebrew script? I had installed mkcert in a local node.js app so maybe it conflicted? I have removed it and reinstalled from brew but still getting unknown option errors..

**Comment by kopeboy** [comment]
Also, is it normal that **mkcert --help** output doesn't contain the important -install option!?
```
Usage: mkcert [options] [command]

Options:
  -V, --version                             output the version number
  -h, --help                                display help for command

Commands:
  create-ca [options]
  create-cert|create-certificate [options]
  help [command]                            display help for command
```

**Comment by kopeboy** [comment]
I have 466 certificates on my machine, I don't even know where to start 😅
![image](https://github.com/FiloSottile/mkcert/assets/4728367/8489194b-4cb6-4ffd-b603-ef8bca55e5e3)

**Comment by rfay** [comment]
Your mkcert is not the mkcert from this project. You should close this issue and install the mkcert from this project, thanks!

**Comment by ctrl-alter-ego** [comment]
I also had this problem (yes, with this project) and switching into `zsh` before running `mkcert -install` worked for me.
