### ISSUE TITLE
Why is it impossible to remove this library and remove the rootCA-key.pem?

### ISSUE THREAD

**Issue by mhmdsalahsebai** [FiloSottile/mkcert#576]
## Environment

* Operating system (Fedora 39):
* mkcert version (from `mkcert -version`): v1.4.4
* Server (where the certificate is loaded):
* Client (e.g. browser, CLI tool, or script):

## What you did

I followed the instructions in the README for installation and followed this to remove the certificate: [how to uninstall](https://github.com/FiloSottile/mkcert/issues/208)

## What went wrong

After uninstalling the certificate and removing the root CA from your home directory, the rootCA-key.pem and the certificate keep showing up! Is there a way to remove this?

**Comment by PaulVe2024** [comment]
@mhmdsalahsebai 
So what was real problem and solution ?

ref #202
