### ISSUE TITLE
Firefox Support?

### ISSUE THREAD

**Issue by troyxmccall** [FiloSottile/mkcert#6]
This works flawlessly with Chrome, Safari, & Opera - so thank you for that.

Firefox doesn't seem to trust the issuer - I can add an exception to Firefox as a workaround (which I've done in the past for local cert authorities) 

```
test.vm uses an invalid security certificate. 
The certificate is not trusted because the issuer certificate is unknown. 
The server might not be sending the appropriate intermediate certificates. 
An additional root certificate may need to be imported. 
Error code: SEC_ERROR_UNKNOWN_ISSUER


Peer’s Certificate issuer is not recognized. 
HTTP Strict Transport Security: false 
HTTP Public Key Pinning: false 
```

would be happy to supply more details if needed, 

rootCA is installed on my host machine (OSX) and is in a NFS mounted folder shared with a vagrant Centos7/Apache 2.4.6 box

**Comment by troyxmccall** [comment]
update: I manually installed the rootCA in firefox through firefox's cert manager 

![screenshot 2018-06-27 11 52 52](https://user-images.githubusercontent.com/129784/41985238-bf6327ba-7a00-11e8-993a-0c506f03a48e.png)

Prefences -> Privacy & Security -> Certificates -> View Certificates -> Authorities (Tab) -> Import

and that works, not sure if that can be automated.

**Comment by adamdecaf** [comment]
This will need done with `certutil` from NSS. https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Reference/NSS_tools_:_certutil 

An aside: I've been [slowly] working on a tool to add/list/delete certificates across platforms/apps, but doing this for NSS is petty simple.

https://github.com/adamdecaf/cert-manage/blob/master/pkg/store/nss.go#L359-L383 

@FiloSottile how interested are you in a library to better handle cert CRUD operations?

**Comment by kanlukasz** [comment]
Hello @troyxmccall. Does your method still work in Firefox?

**Comment by troyxmccall** [comment]
@kanlukasz this has been automated per the docset (you need NSS) - macOS and Linux support only

https://github.com/FiloSottile/mkcert#macos

**Comment by kanlukasz** [comment]
Thanks for reply. I solved it with this https://github.com/FiloSottile/mkcert/issues/239 for Windows 😉

**Comment by DanielSiepmann** [comment]
I'm wondering what I'm doing wrong.
I've installed mkcert via nix-env on Ubuntu and had it setup through custom compilation beforehand.
It generated a new files in `~/.local/share/mkcert/` and added them to the browsers.

I'm able to use `wget`, but Firefox and Chromium still show `Error code: SEC_ERROR_UNKNOWN_ISSUER`. When following the older comment, Firefox tells me: `This certificate is already installed as a certificate authority.`

Would be cool to become a hint what's wrong with my setup.

Older certificates (generated via custom compiled mkcert) are still valid inside of Firefox.

**Comment by kanlukasz** [comment]
> 
> 
> I'm wondering what I'm doing wrong.
> I've installed mkcert via nix-env on Ubuntu and had it setup through custom compilation beforehand.
> It generated a new files in `~/.local/share/mkcert/` and added them to the browsers.
> 
> I'm able to use `wget`, but Firefox and Chromium still show `Error code: SEC_ERROR_UNKNOWN_ISSUER`. When following the older comment, Firefox tells me: `This certificate is already installed as a certificate authority.`
> 
> Would be cool to become a hint what's wrong with my setup.
> 
> Older certificates (generated via custom compiled mkcert) are still valid inside of Firefox.

This issue is closed
I think you should create a new separate issue
