### ISSUE TITLE
Is there a way to generate PKCS#1 RSA keys?

### ISSUE THREAD

**Issue by drusellers** [FiloSottile/mkcert#69]
basically looking to generate a key with the header 

`-----BEGIN RSA PRIVATE KEY-----`

Something that is similar to what is generated by this: https://github.com/SergioBenitez/Rocket/blob/master/examples/tls/private/gen_cert.sh 

Thank you for this work!

**Comment by FiloSottile** [comment]
What software do you need it for? Most should recognize the PKCS#8 keys that mkcert generates, as these days it's even the default generated by openssl.

Anyway you can convert them like this:

```
openssl rsa -in example.com-key.pem -out example.com-key-pkcs1.pem
```

I'd rather not add a flag to mkcert unless there is a lot of requests for the feature.

**Comment by drusellers** [comment]
@FiloSottile the rust web project Rocket is apparently using a lib that was expecting it. I don't have all of the terminology down so I was surprised it didn't work out of the box. Knowing how many options `openssl` has I thought a few different output options might be on the horizon. :) but i totally appreciate keeping your project simple!

**Comment by FiloSottile** [comment]
Thanks for understanding and I hope the command above worked to convert it.

You might want to consider opening an issue with Rocket to support PKCS#8 encoded private keys?

**Comment by lopezator** [comment]
I have a related issue.

Sometimes I'm given certs that use the:

"PRIVATE RSA KEY" header and want to import them using mkcert.

I ended up by editing manually the headers to "PRIVATE KEY".

Changing this condition:

https://github.com/FiloSottile/mkcert/blob/master/cert.go#L301-L303

To:

```
if keyDERBlock == nil || (keyDERBlock.Type != "PRIVATE KEY" && keyDERBlock.Type != "RSA PRIVATE KEY") {
    log.Fatalln("ERROR: failed to read the CA key: unexpected content")
}
```

Would this have any sense? Or the formats are just incompatible and wouldn't work?

**Comment by den-is** [comment]
Encounter same issue when certificate starts with the `-----BEGIN RSA PRIVATE KEY-----`
