### ISSUE TITLE
How to use on Windows

### ISSUE THREAD

**Issue by ivangretsky** [FiloSottile/mkcert#73]
Good day!

This project is something I've been dreaming to happen for a long time. And now it is ready for Windows so a dream comes true) Thanks for this!

I did try to install and make it work, but could not cope and do not know what to do next.

What I did:

1. Downloaded **mkcert-v1.1.2-windows-amd64.exe** from [here](https://github.com/FiloSottile/mkcert/releases/tag/v1.1.2).
2. Moved the file to a folder in Windows path and renamed it to mkcert.exe so it could be called from **cmd** with just `mkcert`.
3. In **cmd** ran `mkcert -install`. There was a popup to confirm adding local CA to trusted system store (or something like that). I agreed. There was all the expected messages in the **cmd**. Two files were added to `C:\Users\ХХХ\AppData\Local\mkcert\`: **rootCA.pem** and **rootCA-key.pem**.
4. Ran `mkcert test.xyz`. Two files were added to `C:\Users\XXX\`: **test.xyz.pem** and **test.xyz-key.pem** (is it the right place to add them???)
5. Launched a local dev server with the **test.xyz** configured to be served both on http and https.
6. Opened Chrome (Firefox is said to be not supported). Entered **https://test.xyz** in the address bar.
7. Got an `ERR_SSL_SERVER_CERT_BAD_FORMAT` error.

What did i do wrong? How can I debug?

**Comment by xyzdata** [comment]
# docs for windows is wanted.

**Comment by xgqfrms** [comment]
# what's wrong with this ?

![image](https://user-images.githubusercontent.com/7291672/45550969-0def7180-b85f-11e8-8b0d-5d58015762f7.png)

**Comment by ivangretsky** [comment]
@xgqfrms, see 1 and 2 in my original post. Real problems start later)

**Comment by xgqfrms** [comment]
@ivangretsky 

# solution

> remame `.exe` & cd to the right `path`

![image](https://user-images.githubusercontent.com/7291672/45552246-e4384980-b862-11e8-9544-48e3f32f1aef.png)

# but the * is not work, why?

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/45554816-d0dcac80-b869-11e8-99a6-53467e43f354.png)

# OK
> https & express sever

```js
const https = require('https');
const express = require('express');
const fs = require('fs');

// const fs = require('fs');

// OpenSSL
// const privateKey = fs.readFileSync('./https-ssl/server.key');
// const certificate = fs.readFileSync('./https-ssl/server.crt');

// pem
const privateKey = fs.readFileSync('./ssl/webgeeker.xyz+3-key.pem');
const certificate = fs.readFileSync('./ssl/webgeeker.xyz+3.pem');

const credentials = {
    key: privateKey,
    cert: certificate,
};

const app = express();
// const app = express.createServer(credentials);
// https://localhost:8888

https.createServer(credentials, app).listen(8888);

app.get('/', function (req, res) {
    console.log('req =', req);
    res.header('Content-type', 'text/html');
    return res.end('<h1>Hello, HTTPS!</h1>');
});


```

**Comment by adamdecaf** [comment]
Was this problem solved?

**Comment by ivangretsky** [comment]
Nope

**Comment by adamdecaf** [comment]
What problem are you having? It looks like someone posted a nodejs server. Is your problem related to the certificate in Window's store or your application?

**Comment by ivangretsky** [comment]
I tried my best to describe my issue in the original post. Do I need to add something?

**Comment by adamdecaf** [comment]
Does the dev server report errors about the certificate files? Can you share the logs and code for the server?

**Comment by aweber1** [comment]
@ivangretsky you mentioned:
> 5. Launched a local dev server with the test.xyz configured to be served both on http and https. 

It's unclear what type of server you're trying to use the certificate with. That will have an impact on both how you generate and how the certificate is used.

That said, if you're using IIS, check out this blog post (shameless plug):
https://medium.com/@aweber01/locally-trusted-development-certificates-with-mkcert-and-iis-e09410d92031

**Comment by ivangretsky** [comment]
I am using xampp portable with apache web server.

Was just writing a long post about how nothing works, checking one step after another, and realized that I did not tell apache to use the certificates issued.  I changed virtual host config for a site as shown below, and it started working!

```
<VirtualHost *:443>
    DocumentRoot "D:/xampp/htdocs/test.xyz"
    ServerName test.xyz
    ServerAlias *.test.xyz
	
    SSLEngine on	
    SSLCertificateFile "c:\Users\XXX\test.xyz.pem"
    SSLCertificateKeyFile "c:\Users\XXX\test.xyz-key.pem"
</VirtualHost>
```
It is in `xampp\apache\conf\extra\httpd-vhosts.conf` in my case for xampp.

Thanks @adamdecaf and @aweber1!

Wildcard for 2nd level domains don't work in Chrome though.

**Comment by Tonzitos** [comment]
![image](https://user-images.githubusercontent.com/36457967/109394941-9b38ba80-7921-11eb-9492-ee7f75cdacf9.png)

I am not sure if my problem is related.

**Comment by Tonzitos** [comment]
![image](https://user-images.githubusercontent.com/36457967/109394988-dd61fc00-7921-11eb-992a-71d9572d6100.png)

I am not sure if my problem is related

**Comment by mohamedmmc** [comment]
> ![image](https://user-images.githubusercontent.com/36457967/109394988-dd61fc00-7921-11eb-992a-71d9572d6100.png)
> 
> I am not sure if my problem is related

i'm dealing with the same issue

**Comment by Marchiuzzz** [comment]
Having the exactly same issue
