### ISSUE TITLE
[Question] How to generate a fullchain cert file? 

### ISSUE THREAD

**Issue by saicrazyfire** [FiloSottile/mkcert#76]
I'm looking to leverage this on internally hosted Home Assistant and they have a Nginx proxy. I want to be able to access the web application via something like "https://hassio.local". I can create the cert and the key with mkcert but the Nginx addon for HA needs the fullchain.

**Comment by adamdecaf** [comment]
There's only the root CA and your leaf certs. When you `mkcert -install` it tells you where the CA certificate is.

```
$ mkcert -install
Created a new local CA at "/home/adam/.local/share/mkcert" 💥
The local CA is now installed in the system trust store! ⚡️
Warning: "certutil" is not available, so the CA can't be automatically installed in Firefox and/or Chrome/Chromium! ⚠️
Install "certutil" with "apt install libnss3-tools" or "yum install nss-tools" and re-run "mkcert -install" 👈

$ ls -l ~/.local/share/mkcert/
total 8
-r-------- 1 adam adam 2484 Oct  2 08:49 rootCA-key.pem
-rw-r--r-- 1 adam adam 1655 Oct  2 08:49 rootCA.pem
```

`mkcert hassio.local` would then generate the leaf cert and key in the directory you call `mkcert` from.

**Comment by saicrazyfire** [comment]
So would it be enough to concatenate rootCA.pem and hassio.pem and have a fullchain.pem? At least from what I could google, the full chain cert is that

**Comment by FiloSottile** [comment]
Since mkcert does not generate intermediate CAs, you should be able to use the certificate alone as "fullchain". If not, you just need to concatenate the file in `$(mkcert -CAROOT)/rootCA.pem`, but browsers don't need the root to be sent to them.

**Comment by BarnabasSzabolcs** [comment]
Unfortunately it looks like python's requests needs it.

**Comment by FiloSottile** [comment]
Should be as simple as

```
mkcert example.com
cat example.com.pem > example.com-fullchain.pem
cat "$(mkcert -CAROOT)/rootCA.pem" >> example.com-fullchain.pem
```

**Comment by BarnabasSzabolcs** [comment]
Thanks a bunch, Filo!

**Comment by emahuni** [comment]
> Should be as simple as
> 
> ```
> mkcert example.com
> cat example.com.pem > example.com-fullchain.pem
> cat "$(mkcert -CAROOT)/rootCA.pem" >> example.com-fullchain.pem
> ```

That's not the fullchain, that's just the chain. Fullchain is the cert.pem at the top + the chain at the bottom.
See #214 for the correct way of generating these files. I do this all the time developing SIP technologies that need SSL. They require these kind of files.

**Comment by tyteen4a03** [comment]
@emahuni do you have the commands to generate this? I can't wrap my head around what certs are needed.

@FiloSottile please reconsider.
