### ISSUE TITLE
Certificates are rejected by Node

### ISSUE THREAD

**Issue by dpraul** [FiloSottile/mkcert#78]
Node uses its own list of accepted CAs, not the system store, thus certificates generated by `mkcert` are rejected by Node requests.

That said, as of Node v7.3.0, Node implements [a `NODE_EXTRA_CA_CERTS` environment variable](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) that can be used to specify extra rootCAs to trust. So it sounds like this could be remedied by setting this environment variable to the rootCA path during `-install`.

**Comment by adamdecaf** [comment]
That's what I have done in the past. How were you suggesting `mkcert` set environment variables? That seems out of scope for `mkcert` and better done by all the local dev / deployment tools.

**Comment by dpraul** [comment]
I figured since the Java trust store was supported it would fall in-scope, but totally understood if that's not the case (if so, maybe a note can be added to the `README` just so others don't experience the issue).

And in regards to how, I assumed that a global environment variable could be set since `mkcert` already makes changes that require elevated permissions. Maybe a guard would be added wherein the env var would not be overwritten if it already exists.

**Comment by FiloSottile** [comment]
Setting global env vars permanently is not easy to do universally and probably unexpected. What we can do though is document how to use `mkcert -CAROOT` to set `NODE_EXTRA_CA_CERTS` in the README.

**Comment by rfay** [comment]
Here's a solution for node, at least it worked for me:
```
export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"
```

**Comment by waldyrious** [comment]
@rfay that is exactly what @FiloSottile added to the README in the [PR that fixed this issue](https://github.com/FiloSottile/mkcert/commit/7fbb1febce3d6098c0e9fb72fba4f2119746c725#diff-04c6e90faac2675aa89e2176d2eec7d8R134).
