### ISSUE TITLE
[DOCKER] Alpine installation

### ISSUE THREAD

**Issue by Guikingone** [FiloSottile/mkcert#79]
Hi everyone, 

Small question about the installation of this tool in a Docker project, I try to install it in a `nginx:alpine` image, the problem is, once go is installed, here's the error that appears: 

```bash
# go get -u github.com/FiloSottile/mkcert
# github.com/FiloSottile/mkcert
root/go/src/github.com/FiloSottile/mkcert/cert.go:87:19: undefined: x509.MarshalPKCS8PrivateKey
root/go/src/github.com/FiloSottile/mkcert/cert.go:198:18: undefined: x509.MarshalPKCS8PrivateKey
root/go/src/github.com/FiloSottile/mkcert/go110min.go:8:9: undefined: ThisProjectRequiresGo1·10OrHigher
root/go/src/github.com/FiloSottile/mkcert/go110min.go:8:31: invalid identifier character U+00B7 '·'
root/go/src/github.com/FiloSottile/mkcert/main.go:53:52: flag.CommandLine.Output undefined (type *flag.FlagSet has no field or method Output, but does have flag.output)
```

I've tried to install it several time (after installing additionals tools) but nothing works, the error stay the same, does anyone has already solved the problem ? 🤔 

Thanks for the help 😃

**Comment by FiloSottile** [comment]
Hi! mkcert requires Go 1.10 or higher to compile, and it looks like you are using an out of date version.
