### ISSUE TITLE
IE & Edge support

### ISSUE THREAD

**Issue by chaitanya11** [FiloSottile/mkcert#80]
Certificate generated is not working with IE 11 & Edge, giving this error (```error code: DLG_FLAGS_INVALID_CA```)

**Comment by FiloSottile** [comment]
Did you run `mkcert -install`? Can you share the output?

**Comment by chaitanya11** [comment]
Here is the output for `mkcert -install `
````
$mkcert -install
Using the local CA at "/Users/danava/Library/Application Support/mkcert" ✨
Password:
The local CA is now installed in the system trust store! ⚡️
Enter Password or Pin for "NSS Certificate DB":
The local CA is now installed in the Firefox trust store (requires browser restart)! 🦊
````

**Comment by adamdecaf** [comment]
Are you running on macOS, but trying to run Microsoft apps in a vm?

**Comment by FiloSottile** [comment]
For mkcert to install the CA in the IE 11 & Edge store, you'll have to run `mkcert -install` on the Windows system.
