### ISSUE TITLE
Certutil error on fresh Mac OS Mojave install

### ISSUE THREAD

**Issue by selfagency** [FiloSottile/mkcert#83]
when i attempt to install mkcert, i get the following error:

```
➜ mkcert -install
Using the local CA at "/Users/daniel/Library/Application Support/mkcert" ✨
Password:
The local CA is now installed in the system trust store! ⚡️
ERROR: failed to execute "certutil -A": exit status 255

certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
```

when i google the issue, it says i need to initialize the nss database. i did this, however, and still get the same error above.

```
➜ ls -la ~/.pki/nssdb/
total 136
drwx------  5 daniel  staff    160 Oct 25 22:45 .
drwxr-xr-x  3 daniel  staff     96 Oct 25 22:44 ..
-rw-------  1 daniel  staff  28672 Oct 25 22:45 cert9.db
-rw-------  1 daniel  staff  36864 Oct 25 22:45 key4.db
-rw-------  1 daniel  staff    431 Oct 25 22:45 pkcs11.txt
```

**Comment by adamdecaf** [comment]
What version are you on? How did you initialize the db?

**Comment by selfagency** [comment]
Mac OS 10.14
mkcert 1.1.2

```
mkdir -p ~/.pki/nssdb
chmod 700 ~/.pki/nssdb
certutil -d $HOME/.pki/nssdb -N
```

also tried
```
certutil -d sql:$HOME/.pki/nssdb -N
```
with the same result

**Comment by adamdecaf** [comment]
Can you delete ~/.pki, load a few https sites in Firefox and then run
mkcert?

**Comment by selfagency** [comment]
same deal

**Comment by selfagency** [comment]
hmm seems to work if i use sudo

**Comment by selfagency** [comment]
ok, so i have both firefox and firefox developer edition installed. after using `sudo`, it added the CA to the developer edition, but not the regular edition. and if i try to do `mkcert -install` without `sudo`, i get the error above.

**Comment by adamdecaf** [comment]
Hmm, is the path different than what's mentioned in https://github.com/FiloSottile/mkcert/issues/51 ?

**Comment by selfagency** [comment]
Both Firefox and Firefox Dev Ed are in /Applications and my data folder is /Users/daniel/Library/Application Support/Firefox.

**Comment by adamdecaf** [comment]
I just realized `~/.pki/nssdb/` is the linux path, what's at this filepath: 

```
$ ls -l ~/Library/Application\ Support/Firefox/Profiles/*.default/ | grep '.db' 
-rw-------@ 1 adam  staff    327680 Nov 10 13:32 cert9.db
-rw-------@ 1 adam  staff    294912 Nov 10 13:32 key4.db
```

**Comment by selfagency** [comment]
```
➜ ls -l ~/Library/Application\ Support/Firefox/Profiles/*.default/ | grep '.db'
-rw-------   1 root    staff     28672 Oct 26 17:08 cert9.db
-rw-------   1 root    staff     36864 Oct 26 17:08 key4.db
```

**Comment by adamdecaf** [comment]
Can `mkcert` read those files? They're owned by root and not world readable.

**Comment by selfagency** [comment]
changing the owner to myself seems to have worked. thanks for your help!

```
➜ sudo chown -R daniel:staff ~/Library/Application\ Support/Firefox/Profiles/*.default/
➜ mkcert -install
Using the local CA at "/Users/daniel/Library/Application Support/mkcert" ✨
```
