### ISSUE TITLE
installJava fails on Windows

### ISSUE THREAD

**Issue by philippbeckmann** [FiloSottile/mkcert#84]
`mkcert.exe -install` with set JAVA_HOME fails with following error:

`ERROR: failed to execute "keytool -importcert": exec: "sudo": executable file not found in %PATH%`

**Comment by adamdecaf** [comment]
Are you running `mkcert.exe` inside Windows Subsystem for Linux (WSL)?

**Comment by philippbeckmann** [comment]
@adamdecaf No, i'm using the more common `cmd.exe` or Powershell on Windows.

**Comment by philippbeckmann** [comment]
I am using this one: [mkcert-v1.1.2-windows-amd64.exe](https://github.com/FiloSottile/mkcert/releases/download/v1.1.2/mkcert-v1.1.2-windows-amd64.exe)

The `sudo` is in [truststore_java.go@L113](https://github.com/FiloSottile/mkcert/blob/fcebdc9845560b3945005932dfc0651ac06d6b98/truststore_java.go#L113)

**Comment by adamdecaf** [comment]
Oh you're totally right. My bad. Can you try out this PR? https://github.com/FiloSottile/mkcert/pull/85

**Comment by philippbeckmann** [comment]
The `sudo` is gone, but the destination file `<JDK>\lib\security\cacerts` is not writeable by a normal user.

I had a look in this issue and it seems the only way to run a command elevated is by using `ShellExecute` with the verb `runas`. 

Alternativly, a manifest file can be added to require elevation on invoking `mkcert` (certainly not desirable, as there are many functions usable without elevation)

Option 3 would be to just fail and instruct the user to run `mkcert` elevated.

**Comment by adamdecaf** [comment]
I recall it being a common pattern to "Run as Administrator" on Windows. If that's still around then that sounds fine.
