### ISSUE TITLE
error: unknown option `-i'

### ISSUE THREAD

**Issue by internationalhouseofdonald** [FiloSottile/mkcert#92]
I am trying to run mkcert within Ubuntu on Windows 10. While reading [this guide](https://github.com/Shopify/slate/wiki/Getting-Started) on how to create a Slate theme for Shopify, I downloaded `brew` on my Ubuntu terminal, then ran `brew install mkcert`. Now, for some reason, when I run `mkcert -install`, it returns:

    error: unknown option `i'

Further, when I tried to run `brew remove mkcert` in an attempt to uninstall and reinstall, mkcert didn't actually get removed during that process and it's just kind of stuck like that now. Has anyone ever seen this before?

![capture](https://user-images.githubusercontent.com/20768148/49394316-27cf8080-f6f9-11e8-8bf2-935fa12be76f.PNG)

It's even doing the same thing when I download from Chocolatey in Powershell.

![capture](https://user-images.githubusercontent.com/20768148/49394475-a0364180-f6f9-11e8-8dbb-7110af0540ee.PNG)

**Comment by adamdecaf** [comment]
I thought homebrew was for macOX only, not Ubuntu. Are you installing [linuxbrew](https://linuxbrew.sh/)? 

FWIW I reinstalled `mkcert` from homebrew and `mkcert -install` works fine on 10.14.1

**Comment by internationalhouseofdonald** [comment]
Yes! Linuxbrew. Sorry. That's what I meant.

**Comment by internationalhouseofdonald** [comment]
Even when I uninstall mkcert with Chocolately, it's just stuck there in my terminal. I can't get rid of it and it's not working properly.

**Comment by internationalhouseofdonald** [comment]
@adamdecaf It says I have 1.1.0. Is there any way I can just uninstall? I don't even see where it's coming from. :\ Kind of dodgy, don't you think?

**Comment by adamdecaf** [comment]
On OSX it's `brew uninstall mkcert`. I don't know what `remove` does.

If you just want the binary gone you can remove it, but there may be cache directories (and the mkcert CA) around still.

```
$ which -a mkcert
/usr/local/bin/mkcert

$ rm /usr/local/bin/mkcert
```

**Comment by adamdecaf** [comment]
We offer Linux install steps, see the readme. 

https://github.com/FiloSottile/mkcert#linux
