### ISSUE TITLE
Error running mkcert-v1.2.0-windows-amd64.exe -install

### ISSUE THREAD

**Issue by DrDrrae** [FiloSottile/mkcert#96]
I'm receiving an error when runing mkcert 1.2.0 on Windows.  I downloaded the prebuilt binary.

Windows 10 1809 17763.195
Running cmd.exe as Administrator.

ERROR: failed to generate CA certificate: asn1: string not valid UTF-8

**Comment by NicolasCARPi** [comment]
What if you try from Powershell.exe instead of cmd.exe?

**Comment by adamdecaf** [comment]
What's the username you're using (on the Windows computer) to run mkcert with? That's put into the certificate.

**Comment by DrDrrae** [comment]
Powershell.exe is the same.

Does the computer get used at any point in the process?  I just remembered that my computer name is "¡" (upside down exclamation point).  I'll try on another computer.

**Comment by adamdecaf** [comment]
Yep. The hostname as well: 

https://github.com/FiloSottile/mkcert/blob/da4da8a4bc86e0dff9c338c547bb1298220d5433/cert.go#L34-L39

**Comment by DrDrrae** [comment]
That's probably the issue.  Doesn't like the upside down exclamation point as the hostname.

**Comment by NicolasCARPi** [comment]
Using non ascii characters as a hostname sounds like a bad idea from the start, but that's just my 2 cents :) (it reminds me of Mac users putting '/' in filenames and not seeing an issue with that)

**Comment by LuomingXu** [comment]
same problem...
Windows, v1.3.0
