### ISSUE TITLE
Add support for ARM or Raspberry Pi3

### ISSUE THREAD

**Issue by elRadix** [FiloSottile/mkcert#97]
Can you please add support for armv7
uname -a= Linux 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

was trying to compile but I hit the wall with this error.
```

root@raspi:~/go/pkg/mod# export GOPATH="/bin/mkcert"
root@raspi:/opt/mkcert-1.2.0# go build
go: finding github.com/DHowett/go-plist v0.0.0-20180609054337-500bd5b9081b
go: finding golang.org/x/text v0.3.0
go: finding golang.org/x/net v0.0.0-20180627171509-e514e69ffb8b
go: finding software.sslmate.com/src/go-pkcs12 v0.0.0-20180114231543-2291e8f0f237
go: downloading golang.org/x/net v0.0.0-20180627171509-e514e69ffb8b
go: downloading software.sslmate.com/src/go-pkcs12 v0.0.0-20180114231543-2291e8f0f237
go: downloading golang.org/x/text v0.3.0
root@raspi:/opt/mkcert-1.2.0# mkcert
-bash: mkcert: command not found
root@raspi:/opt/mkcert-1.2.0# which mkcert
root@raspi:/opt/mkcert-1.2.0# go version
go version go1.11.4 linux/arm
```

**Comment by FiloSottile** [comment]
Your Go version is too old, please try with Go 1.11 and reopen this if it still doesn’t work.

**Comment by FiloSottile** [comment]
Just saw your edit. You built it successfully, it’s just not installed in your PATH. Try “./mkcert”.

**Comment by int3l** [comment]
It seems that RPi 2/3 is supported. I just cross cross compiled the latest version.

For RPi 2/3 you can do the following:
```
bash
# On build machine
git clone --recurse-submodules https://github.com/FiloSottile/mkcert.git
GOARM=7 GOOS=linux GOARCH=arm go build -o "mkcert-$(git describe --tags)-linux-arm7"

# cp the resulting binary mkcert-<version>-linux-arm7 to RPi
sudo apt update && sudo apt upgrade -y
sudo apt install libnss3-tools
sudo install mkcert /usr/local/bin
```

**Comment by FiloSottile** [comment]
Done. Picked GOARM=6 to support all RPi models.

**Comment by erosenberg** [comment]
@FiloSottile - I noticed the latest release for arm doesn't specify v7... `mkcert-v1.4.2-linux-arm`
Is this compatible with Raspberry Pi 2/3? Or do I need to generate something different than what you have listed on your Releases page?

**Comment by int3l** [comment]
@erosenberg It should be compatible - the incentive for using v6 is to make the resulting binary more compatible in order to run on older RPi models. But if you wish, you can recompile it for v7 - it can give you a little bit of (negligible) speedup.
